###############################################################################
#
# Created by PrimeTime on Wed Aug 26 17:45:21 2020
#
###############################################################################
# 
# Written by HyperScale Constraint Extractor
# Version : M-2017.06-SP1
# Top design name : cmsdk_mcu
# Block name : MemContext1
# Extraction Mode : normal
# Instance : u_mem_context1
# 
###############################################################################
set_units -time ns -capacitance pF -current mA -voltage V -resistance kOhm -power pW
###############################################################################
#  
# Units
# capacitive_load_unit           : 1 pF
# current_unit                   : 0.001 A
# resistance_unit                : 1 kOhm
# time_unit                      : 1 ns
# voltage_unit                   : 1 V
###############################################################################
set_operating_conditions -analysis_type on_chip_variation  -library [get_libs {scadv10_cln65gp_rvt_tt_1p0v_25c.db:scadv10_cln65gp_rvt_tt_1p0v_25c}] 
create_clock -name XTAL1 -period 2.5 -waveform { 0 1.25 } -add [get_ports {gated_hclk}]
###############################################################################
#
# Created by pt_shell on Wed Aug 26 17:45:21 2020
#
###############################################################################
# 
# Written by HyperScale Constraint Extractor
# Version : M-2017.06-SP1
# Top design name : cmsdk_mcu
# Block name : MemContext1
# Extraction Mode : normal
# Instance : u_mem_context1
# 
###############################################################################
set_clock_map XTAL1 -parent_clock XTAL1
###############################################################################
# Boundary Context Information
###############################################################################
set_max_capacitance  0.152723 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_chip_select}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_chip_select}]
set_max_capacitance  0.152723 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_n3}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_n3}]
set_max_capacitance  0.152723 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[23]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[23]}]
set_max_capacitance  0.152723 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[22]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[22]}]
set_max_capacitance  0.152723 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[21]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[21]}]
set_max_capacitance  0.152723 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[20]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[20]}]
set_max_capacitance  0.152723 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[19]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[19]}]
set_max_capacitance  0.152723 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[18]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[18]}]
set_max_capacitance  0.152723 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[17]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[17]}]
set_max_capacitance  0.152723 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[16]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[16]}]
set_max_capacitance  0.305446 [get_ports {u_ahb_ram_genblk3_SRAMADDR[11]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMADDR[11]}]
set_max_capacitance  0.305446 [get_ports {u_ahb_ram_genblk3_SRAMADDR[10]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMADDR[10]}]
set_max_capacitance  0.213812 [get_ports {u_ahb_ram_genblk3_SRAMADDR[9]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMADDR[9]}]
set_max_capacitance  0.213812 [get_ports {u_ahb_ram_genblk3_SRAMADDR[8]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMADDR[8]}]
set_max_capacitance  0.106906 [get_ports {u_ahb_ram_genblk3_SRAMADDR[7]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMADDR[7]}]
set_max_capacitance  0.106906 [get_ports {u_ahb_ram_genblk3_SRAMADDR[6]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMADDR[6]}]
set_max_capacitance  0.259629 [get_ports {u_ahb_ram_genblk3_SRAMADDR[5]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMADDR[5]}]
set_max_capacitance  0.213812 [get_ports {u_ahb_ram_genblk3_SRAMADDR[4]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMADDR[4]}]
set_max_capacitance  0.305446 [get_ports {u_ahb_ram_genblk3_SRAMADDR[3]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMADDR[3]}]
set_max_capacitance  0.106906 [get_ports {u_ahb_ram_genblk3_SRAMADDR[2]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMADDR[2]}]
set_max_capacitance  0.106906 [get_ports {u_ahb_ram_genblk3_SRAMADDR[1]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMADDR[1]}]
set_max_capacitance  0.213812 [get_ports {u_ahb_ram_genblk3_SRAMADDR[0]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMADDR[0]}]
set_max_capacitance  1.67995 [get_ports {gated_hclk}]
set_max_transition  0.699428 [get_ports {gated_hclk}]
set_output_delay  0.518594 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[7]}]
set_output_delay  0.101906 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[7]}]
set_output_delay  0.511742 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[7]}]
set_output_delay  0.119465 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[7]}]
set_load -pin_load -max  0.003697 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[7]}]
set_load -pin_load -max  0.003697 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[7]}]
set_load -pin_load -min  0.003697 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[7]}]
set_load -pin_load -min  0.003697 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[7]}]
set_output_delay  0.478989 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[6]}]
set_output_delay  0.085108 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[6]}]
set_output_delay  0.471669 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[6]}]
set_output_delay  0.0967646 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[6]}]
set_load -pin_load -max  0.001087 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[6]}]
set_load -pin_load -max  0.001087 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[6]}]
set_load -pin_load -min  0.001087 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[6]}]
set_load -pin_load -min  0.001087 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[6]}]
set_output_delay  0.492724 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[5]}]
set_output_delay  0.0931042 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[5]}]
set_output_delay  0.47697 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[5]}]
set_output_delay  0.098216 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[5]}]
set_load -pin_load -max  0.001087 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[5]}]
set_load -pin_load -max  0.001087 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[5]}]
set_load -pin_load -min  0.001087 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[5]}]
set_load -pin_load -min  0.001087 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[5]}]
set_output_delay  0.470035 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[4]}]
set_output_delay  0.0905379 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[4]}]
set_output_delay  0.468805 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[4]}]
set_output_delay  0.0983489 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[4]}]
set_load -pin_load -max  0.001087 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[4]}]
set_load -pin_load -max  0.001087 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[4]}]
set_load -pin_load -min  0.001087 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[4]}]
set_load -pin_load -min  0.001087 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[4]}]
set_output_delay  0.477704 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[3]}]
set_output_delay  0.0933778 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[3]}]
set_output_delay  0.462183 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[3]}]
set_output_delay  0.0918264 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[3]}]
set_load -pin_load -max  0.001087 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[3]}]
set_load -pin_load -max  0.001087 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[3]}]
set_load -pin_load -min  0.001087 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[3]}]
set_load -pin_load -min  0.001087 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[3]}]
set_output_delay  0.516875 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[2]}]
set_output_delay  0.137735 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[2]}]
set_output_delay  0.493343 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[2]}]
set_output_delay  0.125859 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[2]}]
set_load -pin_load -max  0.001915 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[2]}]
set_load -pin_load -max  0.001915 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[2]}]
set_load -pin_load -min  0.001915 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[2]}]
set_load -pin_load -min  0.001915 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[2]}]
set_output_delay  0.491273 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[1]}]
set_output_delay  0.100491 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[1]}]
set_output_delay  0.471056 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[1]}]
set_output_delay  0.105663 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[1]}]
set_load -pin_load -max  0.001087 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[1]}]
set_load -pin_load -max  0.001087 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[1]}]
set_load -pin_load -min  0.001087 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[1]}]
set_load -pin_load -min  0.001087 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[1]}]
set_output_delay  0.488606 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[0]}]
set_output_delay  0.0843124 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[0]}]
set_output_delay  0.46616 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[0]}]
set_output_delay  0.0877797 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[0]}]
set_load -pin_load -max  0.001733 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[0]}]
set_load -pin_load -max  0.001733 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[0]}]
set_load -pin_load -min  0.001733 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[0]}]
set_load -pin_load -min  0.001733 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[0]}]
set_driving_cell -rise -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell NAND2BX1MA10TR -from_pin AN -pin Y -input_transition_rise 0.0848345  -input_transition_fall 0.0602898  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_chip_select}]
set_driving_cell -fall -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell NAND2BX1MA10TR -from_pin AN -pin Y -input_transition_rise 0.0848345  -input_transition_fall 0.0602898  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_chip_select}]
set_driving_cell -rise -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell NAND2BX1MA10TR -from_pin B -pin Y -input_transition_rise 0.0634574  -input_transition_fall 0.0346326  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_chip_select}]
set_driving_cell -fall -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell NAND2BX1MA10TR -from_pin B -pin Y -input_transition_rise 0.0634574  -input_transition_fall 0.0346326  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_chip_select}]
set_input_delay  0.941059 -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_chip_select}]
set_input_delay  0.737655 -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_chip_select}]
set_input_delay  0.987789 -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_chip_select}]
set_input_delay  0.775367 -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_chip_select}]
set_input_delay  2.30814 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_chip_select}]
set_input_delay  0.592246 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_chip_select}]
set_input_delay  2.37389 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_chip_select}]
set_input_delay  0.621231 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_chip_select}]
# set_case_analysis 1 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2__Logic1_}]
# set_case_analysis 0 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2__Logic0_}]
set_driving_cell -rise -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell NAND2X1AA10TR -from_pin B -pin Y -input_transition_rise 0.122248  -input_transition_fall 0.100709  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_n3}]
set_driving_cell -fall -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell NAND2X1AA10TR -from_pin B -pin Y -input_transition_rise 0.122248  -input_transition_fall 0.100709  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_n3}]
set_driving_cell -rise -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell NAND2X1AA10TR -from_pin A -pin Y -input_transition_rise 0.0245047  -input_transition_fall 0.0190726  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_n3}]
set_driving_cell -fall -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell NAND2X1AA10TR -from_pin A -pin Y -input_transition_rise 0.0245047  -input_transition_fall 0.0190726  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_n3}]
set_input_delay  0.963177 -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_n3}]
set_input_delay  0.840952 -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_n3}]
set_input_delay  0.979876 -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_n3}]
set_input_delay  0.88412 -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_n3}]
set_input_delay  2.33026 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_n3}]
set_input_delay  0.754987 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_n3}]
set_input_delay  2.36597 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_n3}]
set_input_delay  0.771833 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_n3}]
set_driving_cell -rise -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXT2X1MA10TR -from_pin S0 -pin Y -input_transition_rise 0.377005  -input_transition_fall 0.215338  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[23]}]
set_driving_cell -fall -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXT2X1MA10TR -from_pin S0 -pin Y -input_transition_rise 0.377005  -input_transition_fall 0.215338  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[23]}]
set_driving_cell -rise -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXT2X1MA10TR -from_pin B -pin Y -input_transition_rise 0.0211367  -input_transition_fall 0.0154739  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[23]}]
set_driving_cell -fall -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXT2X1MA10TR -from_pin B -pin Y -input_transition_rise 0.0211367  -input_transition_fall 0.0154739  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[23]}]
set_input_delay  0.724656 -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[23]}]
set_input_delay  0.693996 -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[23]}]
set_input_delay  0.888618 -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[23]}]
set_input_delay  0.868876 -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[23]}]
set_input_delay  1.43615 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[23]}]
set_input_delay  0.562976 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[23]}]
set_input_delay  1.59381 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[23]}]
set_input_delay  0.647392 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[23]}]
set_driving_cell -rise -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXT2X1MA10TR -from_pin S0 -pin Y -input_transition_rise 0.37701  -input_transition_fall 0.215338  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[22]}]
set_driving_cell -fall -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXT2X1MA10TR -from_pin S0 -pin Y -input_transition_rise 0.37701  -input_transition_fall 0.215338  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[22]}]
set_driving_cell -rise -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXT2X1MA10TR -from_pin B -pin Y -input_transition_rise 0.021186  -input_transition_fall 0.0155075  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[22]}]
set_driving_cell -fall -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXT2X1MA10TR -from_pin B -pin Y -input_transition_rise 0.021186  -input_transition_fall 0.0155075  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[22]}]
set_input_delay  0.770109 -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[22]}]
set_input_delay  0.737622 -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[22]}]
set_input_delay  0.962372 -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[22]}]
set_input_delay  0.943384 -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[22]}]
set_input_delay  1.4904 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[22]}]
set_input_delay  0.591718 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[22]}]
set_input_delay  1.6929 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[22]}]
set_input_delay  0.703852 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[22]}]
set_driving_cell -rise -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXT2X1MA10TR -from_pin S0 -pin Y -input_transition_rise 0.377056  -input_transition_fall 0.215338  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[21]}]
set_driving_cell -fall -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXT2X1MA10TR -from_pin S0 -pin Y -input_transition_rise 0.377056  -input_transition_fall 0.215338  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[21]}]
set_driving_cell -rise -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXT2X1MA10TR -from_pin B -pin Y -input_transition_rise 0.0166756  -input_transition_fall 0.0130023  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[21]}]
set_driving_cell -fall -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXT2X1MA10TR -from_pin B -pin Y -input_transition_rise 0.0166756  -input_transition_fall 0.0130023  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[21]}]
set_input_delay  0.666511 -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[21]}]
set_input_delay  0.637621 -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[21]}]
set_input_delay  0.809934 -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[21]}]
set_input_delay  0.788668 -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[21]}]
set_input_delay  1.37851 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[21]}]
set_input_delay  0.531077 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[21]}]
set_input_delay  1.53854 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[21]}]
set_input_delay  0.597213 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[21]}]
set_driving_cell -rise -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXT2X1MA10TR -from_pin S0 -pin Y -input_transition_rise 0.37702  -input_transition_fall 0.215338  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[20]}]
set_driving_cell -fall -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXT2X1MA10TR -from_pin S0 -pin Y -input_transition_rise 0.37702  -input_transition_fall 0.215338  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[20]}]
set_driving_cell -rise -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXT2X1MA10TR -from_pin B -pin Y -input_transition_rise 0.0310344  -input_transition_fall 0.028266  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[20]}]
set_driving_cell -fall -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXT2X1MA10TR -from_pin B -pin Y -input_transition_rise 0.0310344  -input_transition_fall 0.028266  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[20]}]
set_input_delay  0.722206 -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[20]}]
set_input_delay  0.691746 -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[20]}]
set_input_delay  0.893067 -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[20]}]
set_input_delay  0.873045 -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[20]}]
set_input_delay  1.45548 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[20]}]
set_input_delay  0.540886 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[20]}]
set_input_delay  1.64534 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[20]}]
set_input_delay  0.63813 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[20]}]
set_driving_cell -rise -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXT2X1MA10TR -from_pin S0 -pin Y -input_transition_rise 0.377051  -input_transition_fall 0.215338  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[19]}]
set_driving_cell -fall -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXT2X1MA10TR -from_pin S0 -pin Y -input_transition_rise 0.377051  -input_transition_fall 0.215338  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[19]}]
set_driving_cell -rise -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXT2X1MA10TR -from_pin B -pin Y -input_transition_rise 0.0215341  -input_transition_fall 0.0156992  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[19]}]
set_driving_cell -fall -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXT2X1MA10TR -from_pin B -pin Y -input_transition_rise 0.0215341  -input_transition_fall 0.0156992  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[19]}]
set_input_delay  0.73722 -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[19]}]
set_input_delay  0.708156 -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[19]}]
set_input_delay  0.916569 -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[19]}]
set_input_delay  0.896219 -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[19]}]
set_input_delay  1.46404 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[19]}]
set_input_delay  0.564805 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[19]}]
set_input_delay  1.66115 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[19]}]
set_input_delay  0.652911 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[19]}]
set_driving_cell -rise -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXT2X1MA10TR -from_pin S0 -pin Y -input_transition_rise 0.377034  -input_transition_fall 0.215338  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[18]}]
set_driving_cell -fall -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXT2X1MA10TR -from_pin S0 -pin Y -input_transition_rise 0.377034  -input_transition_fall 0.215338  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[18]}]
set_driving_cell -rise -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXT2X1MA10TR -from_pin B -pin Y -input_transition_rise 0.0294366  -input_transition_fall 0.0272761  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[18]}]
set_driving_cell -fall -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXT2X1MA10TR -from_pin B -pin Y -input_transition_rise 0.0294366  -input_transition_fall 0.0272761  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[18]}]
set_input_delay  0.73208 -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[18]}]
set_input_delay  0.703423 -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[18]}]
set_input_delay  0.908129 -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[18]}]
set_input_delay  0.88866 -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[18]}]
set_input_delay  1.44651 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[18]}]
set_input_delay  0.528237 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[18]}]
set_input_delay  1.6388 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[18]}]
set_input_delay  0.616542 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[18]}]
set_driving_cell -rise -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXT2X1MA10TR -from_pin S0 -pin Y -input_transition_rise 0.376877  -input_transition_fall 0.215339  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[17]}]
set_driving_cell -fall -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXT2X1MA10TR -from_pin S0 -pin Y -input_transition_rise 0.376877  -input_transition_fall 0.215339  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[17]}]
set_driving_cell -rise -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXT2X1MA10TR -from_pin B -pin Y -input_transition_rise 0.0175517  -input_transition_fall 0.0134887  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[17]}]
set_driving_cell -fall -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXT2X1MA10TR -from_pin B -pin Y -input_transition_rise 0.0175517  -input_transition_fall 0.0134887  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[17]}]
set_input_delay  0.694103 -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[17]}]
set_input_delay  0.664392 -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[17]}]
set_input_delay  0.839904 -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[17]}]
set_input_delay  0.819022 -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[17]}]
set_input_delay  1.40277 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[17]}]
set_input_delay  0.510292 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[17]}]
set_input_delay  1.56307 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[17]}]
set_input_delay  0.55942 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[17]}]
set_driving_cell -rise -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXT2X1MA10TR -from_pin S0 -pin Y -input_transition_rise 0.376885  -input_transition_fall 0.215339  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[16]}]
set_driving_cell -fall -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXT2X1MA10TR -from_pin S0 -pin Y -input_transition_rise 0.376885  -input_transition_fall 0.215339  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[16]}]
set_driving_cell -rise -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXT2X1MA10TR -from_pin B -pin Y -input_transition_rise 0.0199484  -input_transition_fall 0.0194798  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[16]}]
set_driving_cell -fall -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXT2X1MA10TR -from_pin B -pin Y -input_transition_rise 0.0199484  -input_transition_fall 0.0194798  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[16]}]
set_input_delay  0.70639 -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[16]}]
set_input_delay  0.674933 -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[16]}]
set_input_delay  0.846582 -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[16]}]
set_input_delay  0.825818 -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[16]}]
set_input_delay  1.41337 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[16]}]
set_input_delay  0.501467 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[16]}]
set_input_delay  1.55789 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[16]}]
set_input_delay  0.535363 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[16]}]
set_driving_cell -rise -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXIT2X2MA10TR -from_pin S0 -pin Y -input_transition_rise 0.229508  -input_transition_fall 0.133313  [get_ports {u_ahb_ram_genblk3_SRAMADDR[11]}]
set_driving_cell -fall -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXIT2X2MA10TR -from_pin S0 -pin Y -input_transition_rise 0.229508  -input_transition_fall 0.133313  [get_ports {u_ahb_ram_genblk3_SRAMADDR[11]}]
set_driving_cell -rise -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXIT2X2MA10TR -from_pin A -pin Y -input_transition_rise 0.0335461  -input_transition_fall 0.0204112  [get_ports {u_ahb_ram_genblk3_SRAMADDR[11]}]
set_driving_cell -fall -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXIT2X2MA10TR -from_pin A -pin Y -input_transition_rise 0.0335461  -input_transition_fall 0.0204112  [get_ports {u_ahb_ram_genblk3_SRAMADDR[11]}]
set_input_delay  0.886851 -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[11]}]
set_input_delay  0.851215 -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[11]}]
set_input_delay  0.959128 -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[11]}]
set_input_delay  0.913707 -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[11]}]
set_input_delay  2.27295 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[11]}]
set_input_delay  0.485429 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[11]}]
set_input_delay  2.34523 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[11]}]
set_input_delay  0.545431 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[11]}]
set_driving_cell -rise -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXIT2X2MA10TR -from_pin S0 -pin Y -input_transition_rise 0.229354  -input_transition_fall 0.13315  [get_ports {u_ahb_ram_genblk3_SRAMADDR[10]}]
set_driving_cell -fall -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXIT2X2MA10TR -from_pin S0 -pin Y -input_transition_rise 0.229354  -input_transition_fall 0.13315  [get_ports {u_ahb_ram_genblk3_SRAMADDR[10]}]
set_driving_cell -rise -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXIT2X2MA10TR -from_pin A -pin Y -input_transition_rise 0.0320619  -input_transition_fall 0.0213978  [get_ports {u_ahb_ram_genblk3_SRAMADDR[10]}]
set_driving_cell -fall -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXIT2X2MA10TR -from_pin A -pin Y -input_transition_rise 0.0320619  -input_transition_fall 0.0213978  [get_ports {u_ahb_ram_genblk3_SRAMADDR[10]}]
set_input_delay  0.906584 -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[10]}]
set_input_delay  0.87187 -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[10]}]
set_input_delay  0.987359 -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[10]}]
set_input_delay  0.942843 -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[10]}]
set_input_delay  2.29268 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[10]}]
set_input_delay  0.633532 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[10]}]
set_input_delay  2.37346 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[10]}]
set_input_delay  0.702907 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[10]}]
set_driving_cell -rise -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXIT2X1P4MA10TR -from_pin S0 -pin Y -input_transition_rise 0.229051  -input_transition_fall 0.13285  [get_ports {u_ahb_ram_genblk3_SRAMADDR[9]}]
set_driving_cell -fall -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXIT2X1P4MA10TR -from_pin S0 -pin Y -input_transition_rise 0.229051  -input_transition_fall 0.13285  [get_ports {u_ahb_ram_genblk3_SRAMADDR[9]}]
set_driving_cell -rise -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXIT2X1P4MA10TR -from_pin A -pin Y -input_transition_rise 0.0265975  -input_transition_fall 0.0173546  [get_ports {u_ahb_ram_genblk3_SRAMADDR[9]}]
set_driving_cell -fall -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXIT2X1P4MA10TR -from_pin A -pin Y -input_transition_rise 0.0265975  -input_transition_fall 0.0173546  [get_ports {u_ahb_ram_genblk3_SRAMADDR[9]}]
set_input_delay  0.932461 -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[9]}]
set_input_delay  0.890873 -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[9]}]
set_input_delay  1.01533 -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[9]}]
set_input_delay  0.968962 -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[9]}]
set_input_delay  2.31856 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[9]}]
set_input_delay  0.515312 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[9]}]
set_input_delay  2.40143 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[9]}]
set_input_delay  0.592919 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[9]}]
set_driving_cell -rise -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXIT2X1P4MA10TR -from_pin S0 -pin Y -input_transition_rise 0.229752  -input_transition_fall 0.132852  [get_ports {u_ahb_ram_genblk3_SRAMADDR[8]}]
set_driving_cell -fall -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXIT2X1P4MA10TR -from_pin S0 -pin Y -input_transition_rise 0.229752  -input_transition_fall 0.132852  [get_ports {u_ahb_ram_genblk3_SRAMADDR[8]}]
set_driving_cell -rise -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXIT2X1P4MA10TR -from_pin A -pin Y -input_transition_rise 0.0466113  -input_transition_fall 0.0377659  [get_ports {u_ahb_ram_genblk3_SRAMADDR[8]}]
set_driving_cell -fall -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXIT2X1P4MA10TR -from_pin A -pin Y -input_transition_rise 0.0466113  -input_transition_fall 0.0377659  [get_ports {u_ahb_ram_genblk3_SRAMADDR[8]}]
set_input_delay  0.971181 -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[8]}]
set_input_delay  0.929275 -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[8]}]
set_input_delay  1.06907 -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[8]}]
set_input_delay  1.02277 -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[8]}]
set_input_delay  2.35728 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[8]}]
set_input_delay  0.684796 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[8]}]
set_input_delay  2.45517 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[8]}]
set_input_delay  0.80438 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[8]}]
set_driving_cell -rise -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell FRICGX0P7BA10TR -from_pin CK -pin ECK -input_transition_rise 0.0213696  -input_transition_fall 0.0155057  [get_ports {u_ahb_ram_genblk3_SRAMADDR[7]}]
set_driving_cell -fall -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell FRICGX0P7BA10TR -from_pin CK -pin ECK -input_transition_rise 0.0213696  -input_transition_fall 0.0155057  [get_ports {u_ahb_ram_genblk3_SRAMADDR[7]}]
set_driving_cell -rise -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell FRICGX0P7BA10TR -from_pin CK -pin ECK -input_transition_rise 0.0213596  -input_transition_fall 0.0154921  [get_ports {u_ahb_ram_genblk3_SRAMADDR[7]}]
set_driving_cell -fall -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell FRICGX0P7BA10TR -from_pin CK -pin ECK -input_transition_rise 0.0213596  -input_transition_fall 0.0154921  [get_ports {u_ahb_ram_genblk3_SRAMADDR[7]}]
set_input_delay  1.17651 -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[7]}]
set_input_delay  1.1344 -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[7]}]
set_input_delay  1.27101 -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[7]}]
set_input_delay  1.2244 -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[7]}]
set_input_delay  2.56751 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[7]}]
set_input_delay  0.757852 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[7]}]
set_input_delay  2.69084 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[7]}]
set_input_delay  0.846787 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[7]}]
set_driving_cell -rise -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell FRICGX0P7BA10TR -from_pin CK -pin ECK -input_transition_rise 0.0230182  -input_transition_fall 0.0164888  [get_ports {u_ahb_ram_genblk3_SRAMADDR[6]}]
set_driving_cell -fall -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell FRICGX0P7BA10TR -from_pin CK -pin ECK -input_transition_rise 0.0230182  -input_transition_fall 0.0164888  [get_ports {u_ahb_ram_genblk3_SRAMADDR[6]}]
set_driving_cell -rise -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell FRICGX0P7BA10TR -from_pin CK -pin ECK -input_transition_rise 0.0230145  -input_transition_fall 0.0164741  [get_ports {u_ahb_ram_genblk3_SRAMADDR[6]}]
set_driving_cell -fall -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell FRICGX0P7BA10TR -from_pin CK -pin ECK -input_transition_rise 0.0230145  -input_transition_fall 0.0164741  [get_ports {u_ahb_ram_genblk3_SRAMADDR[6]}]
set_input_delay  1.19471 -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[6]}]
set_input_delay  1.15266 -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[6]}]
set_input_delay  1.29429 -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[6]}]
set_input_delay  1.24794 -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[6]}]
set_input_delay  2.60682 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[6]}]
set_input_delay  0.776366 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[6]}]
set_input_delay  2.69779 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[6]}]
set_input_delay  0.871527 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[6]}]
set_driving_cell -rise -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell BUFX1P7BA10TR -from_pin A -pin Y -input_transition_rise 0.0167411  -input_transition_fall 0.0130439  [get_ports {u_ahb_ram_genblk3_SRAMADDR[5]}]
set_driving_cell -fall -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell BUFX1P7BA10TR -from_pin A -pin Y -input_transition_rise 0.0167411  -input_transition_fall 0.0130439  [get_ports {u_ahb_ram_genblk3_SRAMADDR[5]}]
set_driving_cell -rise -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell BUFX1P7BA10TR -from_pin A -pin Y -input_transition_rise 0.0167409  -input_transition_fall 0.0130436  [get_ports {u_ahb_ram_genblk3_SRAMADDR[5]}]
set_driving_cell -fall -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell BUFX1P7BA10TR -from_pin A -pin Y -input_transition_rise 0.0167409  -input_transition_fall 0.0130436  [get_ports {u_ahb_ram_genblk3_SRAMADDR[5]}]
set_input_delay  1.06016 -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[5]}]
set_input_delay  1.01613 -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[5]}]
set_input_delay  1.09908 -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[5]}]
set_input_delay  1.0551 -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[5]}]
set_input_delay  2.44625 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[5]}]
set_input_delay  0.635212 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[5]}]
set_input_delay  2.50173 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[5]}]
set_input_delay  0.675441 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[5]}]
set_driving_cell -rise -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXIT2X1P4MA10TR -from_pin S0 -pin Y -input_transition_rise 0.22945  -input_transition_fall 0.133246  [get_ports {u_ahb_ram_genblk3_SRAMADDR[4]}]
set_driving_cell -fall -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXIT2X1P4MA10TR -from_pin S0 -pin Y -input_transition_rise 0.22945  -input_transition_fall 0.133246  [get_ports {u_ahb_ram_genblk3_SRAMADDR[4]}]
set_driving_cell -rise -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXIT2X1P4MA10TR -from_pin A -pin Y -input_transition_rise 0.046034  -input_transition_fall 0.0374284  [get_ports {u_ahb_ram_genblk3_SRAMADDR[4]}]
set_driving_cell -fall -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXIT2X1P4MA10TR -from_pin A -pin Y -input_transition_rise 0.046034  -input_transition_fall 0.0374284  [get_ports {u_ahb_ram_genblk3_SRAMADDR[4]}]
set_input_delay  0.985082 -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[4]}]
set_input_delay  0.94302 -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[4]}]
set_input_delay  1.0886 -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[4]}]
set_input_delay  1.04228 -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[4]}]
set_input_delay  2.37118 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[4]}]
set_input_delay  0.720028 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[4]}]
set_input_delay  2.47469 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[4]}]
set_input_delay  0.844558 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[4]}]
set_driving_cell -rise -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXIT2X2MA10TR -from_pin S0 -pin Y -input_transition_rise 0.229521  -input_transition_fall 0.133327  [get_ports {u_ahb_ram_genblk3_SRAMADDR[3]}]
set_driving_cell -fall -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXIT2X2MA10TR -from_pin S0 -pin Y -input_transition_rise 0.229521  -input_transition_fall 0.133327  [get_ports {u_ahb_ram_genblk3_SRAMADDR[3]}]
set_driving_cell -rise -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXIT2X2MA10TR -from_pin A -pin Y -input_transition_rise 0.0290377  -input_transition_fall 0.01872  [get_ports {u_ahb_ram_genblk3_SRAMADDR[3]}]
set_driving_cell -fall -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXIT2X2MA10TR -from_pin A -pin Y -input_transition_rise 0.0290377  -input_transition_fall 0.01872  [get_ports {u_ahb_ram_genblk3_SRAMADDR[3]}]
set_input_delay  0.889849 -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[3]}]
set_input_delay  0.854195 -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[3]}]
set_input_delay  0.961973 -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[3]}]
set_input_delay  0.916677 -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[3]}]
set_input_delay  2.27595 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[3]}]
set_input_delay  0.483962 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[3]}]
set_input_delay  2.34807 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[3]}]
set_input_delay  0.54583 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[3]}]
set_driving_cell -rise -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell FRICGX0P7BA10TR -from_pin CK -pin ECK -input_transition_rise 0.241301  -input_transition_fall 0.154089  [get_ports {u_ahb_ram_genblk3_SRAMADDR[2]}]
set_driving_cell -fall -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell FRICGX0P7BA10TR -from_pin CK -pin ECK -input_transition_rise 0.241301  -input_transition_fall 0.154089  [get_ports {u_ahb_ram_genblk3_SRAMADDR[2]}]
set_driving_cell -rise -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell FRICGX0P7BA10TR -from_pin CK -pin ECK -input_transition_rise 0.230516  -input_transition_fall 0.122662  [get_ports {u_ahb_ram_genblk3_SRAMADDR[2]}]
set_driving_cell -fall -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell FRICGX0P7BA10TR -from_pin CK -pin ECK -input_transition_rise 0.230516  -input_transition_fall 0.122662  [get_ports {u_ahb_ram_genblk3_SRAMADDR[2]}]
set_input_delay  1.11972 -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[2]}]
set_input_delay  1.07746 -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[2]}]
set_input_delay  1.21189 -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[2]}]
set_input_delay  1.16621 -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[2]}]
set_input_delay  2.50582 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[2]}]
set_input_delay  0.802224 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[2]}]
set_input_delay  2.59798 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[2]}]
set_input_delay  0.900477 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[2]}]
set_driving_cell -rise -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell FRICGX0P7BA10TR -from_pin CK -pin ECK -input_transition_rise 0.0172909  -input_transition_fall 0.0132886  [get_ports {u_ahb_ram_genblk3_SRAMADDR[1]}]
set_driving_cell -fall -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell FRICGX0P7BA10TR -from_pin CK -pin ECK -input_transition_rise 0.0172909  -input_transition_fall 0.0132886  [get_ports {u_ahb_ram_genblk3_SRAMADDR[1]}]
set_driving_cell -rise -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell FRICGX0P7BA10TR -from_pin CK -pin ECK -input_transition_rise 0.0172817  -input_transition_fall 0.0132674  [get_ports {u_ahb_ram_genblk3_SRAMADDR[1]}]
set_driving_cell -fall -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell FRICGX0P7BA10TR -from_pin CK -pin ECK -input_transition_rise 0.0172817  -input_transition_fall 0.0132674  [get_ports {u_ahb_ram_genblk3_SRAMADDR[1]}]
set_input_delay  1.23072 -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[1]}]
set_input_delay  1.04799 -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[1]}]
set_input_delay  1.43523 -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[1]}]
set_input_delay  1.16108 -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[1]}]
set_input_delay  2.54251 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[1]}]
set_input_delay  0.706067 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[1]}]
set_input_delay  2.61858 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[1]}]
set_input_delay  0.785546 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[1]}]
set_driving_cell -rise -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXIT2X1P4MA10TR -from_pin S0 -pin Y -input_transition_rise 0.229051  -input_transition_fall 0.13285  [get_ports {u_ahb_ram_genblk3_SRAMADDR[0]}]
set_driving_cell -fall -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXIT2X1P4MA10TR -from_pin S0 -pin Y -input_transition_rise 0.229051  -input_transition_fall 0.13285  [get_ports {u_ahb_ram_genblk3_SRAMADDR[0]}]
set_driving_cell -rise -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXIT2X1P4MA10TR -from_pin A -pin Y -input_transition_rise 0.0418421  -input_transition_fall 0.0348643  [get_ports {u_ahb_ram_genblk3_SRAMADDR[0]}]
set_driving_cell -fall -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXIT2X1P4MA10TR -from_pin A -pin Y -input_transition_rise 0.0418421  -input_transition_fall 0.0348643  [get_ports {u_ahb_ram_genblk3_SRAMADDR[0]}]
set_input_delay  1.06607 -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[0]}]
set_input_delay  0.890037 -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[0]}]
set_input_delay  1.28986 -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[0]}]
set_input_delay  1.02183 -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[0]}]
set_input_delay  2.35544 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[0]}]
set_input_delay  0.68952 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[0]}]
set_input_delay  2.48283 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[0]}]
set_input_delay  0.803963 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[0]}]
set_driving_cell -rise -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell BUFX11BA10TR -from_pin A -pin Y -input_transition_rise 0.0302393  -input_transition_fall 0.0265184  [get_ports {gated_hclk}]
set_driving_cell -fall -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell BUFX11BA10TR -from_pin A -pin Y -input_transition_rise 0.0302393  -input_transition_fall 0.0265184  [get_ports {gated_hclk}]
set_driving_cell -rise -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell BUFX11BA10TR -from_pin A -pin Y -input_transition_rise 0.0302393  -input_transition_fall 0.0264034  [get_ports {gated_hclk}]
set_driving_cell -fall -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell BUFX11BA10TR -from_pin A -pin Y -input_transition_rise 0.0302393  -input_transition_fall 0.0264034  [get_ports {gated_hclk}]
set_clock_latency -source -rise  -clock [get_clocks {XTAL1}]  0.142269 [get_ports {gated_hclk}]
set_clock_latency -source -fall -late  -clock [get_clocks {XTAL1}]  0.13811 [get_ports {gated_hclk}]
set_clock_latency -source -fall -early  -clock [get_clocks {XTAL1}]  0.13803 [get_ports {gated_hclk}]
set_propagated_clock [get_pins {u_part_extmem1/u_mem_ext1/u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_mem0/CLK}]
###############################################################################
# Extra setting
###############################################################################
set timing_input_port_default_clock false
set auto_wire_load_selection false
set_wire_load_mode top
###############################################################################
# POCV Information
###############################################################################
