###############################################################################
#
# Created by PrimeTime on Thu Oct  7 17:38:15 2021
#
###############################################################################
# 
# Written by HyperScale Constraint Extractor
# Version : R-2020.09-SP5
# Top design name : cmsdk_mcu
# Block name : PARTMAIN
# Extraction Mode : normal
# Instance : u_core_context/u_part_main
# 
###############################################################################
set_units -time ns -capacitance pF -current mA -voltage V -resistance kOhm -power pW
###############################################################################
#  
# Units
# capacitive_load_unit           : 1 pF
# current_unit                   : 0.001 A
# resistance_unit                : 1 kOhm
# time_unit                      : 1 ns
# voltage_unit                   : 1 V
###############################################################################
set_operating_conditions -analysis_type on_chip_variation  -library [get_libs {scadv10_cln65gp_rvt_tt_1p0v_25c.db:scadv10_cln65gp_rvt_tt_1p0v_25c}] 
create_clock -name XTAL1 -period 2.5 -waveform { 0 1.25 } -add [get_ports {XTAL1}]
###############################################################################
#
# Created by pt_shell on Thu Oct  7 17:38:15 2021
#
###############################################################################
# 
# Written by HyperScale Constraint Extractor
# Version : R-2020.09-SP5
# Top design name : cmsdk_mcu
# Block name : PARTMAIN
# Extraction Mode : normal
# Instance : u_core_context/u_part_main
# 
###############################################################################
set_clock_map XTAL1 -parent_clock XTAL1
###############################################################################
# Boundary Context Information
###############################################################################
set_max_capacitance  2.443564 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[7]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[7]}]
set_max_capacitance  2.443564 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[6]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[6]}]
set_max_capacitance  2.443564 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[5]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[5]}]
set_max_capacitance  2.443564 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[4]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[4]}]
set_max_capacitance  0.75 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[3]}]
set_max_transition  1 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[3]}]
set_max_capacitance  2.443564 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[2]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[2]}]
set_max_capacitance  2.443564 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[1]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[1]}]
set_max_capacitance  2.443564 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[0]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[0]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_chip_select}]
set_max_capacitance  2.443564 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[7]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[7]}]
set_max_capacitance  2.443564 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[6]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[6]}]
set_max_capacitance  2.443564 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[5]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[5]}]
set_max_capacitance  0.75 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[4]}]
set_max_transition  1 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[4]}]
set_max_capacitance  2.443564 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[3]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[3]}]
set_max_capacitance  2.443564 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[2]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[2]}]
set_max_capacitance  2.443564 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[1]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[1]}]
set_max_capacitance  2.443564 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[0]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[0]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_chip_select}]
set_max_transition  1 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_n3}]
set_max_transition  1 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_n2}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[31]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[30]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[29]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[28]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[27]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[26]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[25]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[24]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[23]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[22]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[21]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[20]}]
set_max_transition  1 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[19]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[18]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[17]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[16]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMADDR[11]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMADDR[10]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMADDR[9]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMADDR[8]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMADDR[7]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMADDR[6]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMADDR[5]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMADDR[4]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMADDR[3]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMADDR[2]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMADDR[1]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMADDR[0]}]
set_max_transition  1 [get_ports {gated_hclk}]
set_input_delay  1.107347 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[7]}]
set_input_delay  1.104084 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[7]}]
set_input_delay  1.059779 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[7]}]
set_input_delay  1.056515 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[7]}]
set_driving_cell -rise -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.141021  -input_transition_fall 0.076686  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[7]}]
set_driving_cell -fall -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.141021  -input_transition_fall 0.076686  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[7]}]
set_driving_cell -rise -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.141021  -input_transition_fall 0.076686  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[7]}]
set_driving_cell -fall -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.141021  -input_transition_fall 0.076686  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[7]}]
set_input_delay  1.109325 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[6]}]
set_input_delay  1.10607 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[6]}]
set_input_delay  1.061476 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[6]}]
set_input_delay  1.058193 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[6]}]
set_driving_cell -rise -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.144865  -input_transition_fall 0.078749  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[6]}]
set_driving_cell -fall -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.144865  -input_transition_fall 0.078749  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[6]}]
set_driving_cell -rise -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.144865  -input_transition_fall 0.078749  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[6]}]
set_driving_cell -fall -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.144865  -input_transition_fall 0.078749  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[6]}]
set_input_delay  1.103487 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[5]}]
set_input_delay  1.10023 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[5]}]
set_input_delay  1.059012 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[5]}]
set_input_delay  1.055734 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[5]}]
set_driving_cell -rise -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.14393  -input_transition_fall 0.078252  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[5]}]
set_driving_cell -fall -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.14393  -input_transition_fall 0.078252  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[5]}]
set_driving_cell -rise -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.14393  -input_transition_fall 0.078252  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[5]}]
set_driving_cell -fall -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.14393  -input_transition_fall 0.078252  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[5]}]
set_input_delay  1.103238 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[4]}]
set_input_delay  1.099986 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[4]}]
set_input_delay  1.05957 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[4]}]
set_input_delay  1.056278 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[4]}]
set_driving_cell -rise -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.13927  -input_transition_fall 0.07573  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[4]}]
set_driving_cell -fall -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.13927  -input_transition_fall 0.07573  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[4]}]
set_driving_cell -rise -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.13927  -input_transition_fall 0.07573  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[4]}]
set_driving_cell -fall -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.13927  -input_transition_fall 0.07573  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[4]}]
set_input_delay  0.969872 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[3]}]
set_input_delay  0.966604 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[3]}]
set_input_delay  0.967455 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[3]}]
set_input_delay  0.964188 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[3]}]
set_driving_cell -rise -max -library USERLIB_nldm_tt_1p00v_1p00v_25c -lib_cell sram_sp_hdc_svt_rvt_hvt -from_pin CLK -pin {Q[3]} -input_transition_rise 0.284712  -input_transition_fall 0.251055  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[3]}]
set_driving_cell -fall -max -library USERLIB_nldm_tt_1p00v_1p00v_25c -lib_cell sram_sp_hdc_svt_rvt_hvt -from_pin CLK -pin {Q[3]} -input_transition_rise 0.284712  -input_transition_fall 0.251055  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[3]}]
set_driving_cell -rise -min -library USERLIB_nldm_tt_1p00v_1p00v_25c -lib_cell sram_sp_hdc_svt_rvt_hvt -from_pin CLK -pin {Q[3]} -input_transition_rise 0.183991  -input_transition_fall 0.15691  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[3]}]
set_driving_cell -fall -min -library USERLIB_nldm_tt_1p00v_1p00v_25c -lib_cell sram_sp_hdc_svt_rvt_hvt -from_pin CLK -pin {Q[3]} -input_transition_rise 0.183991  -input_transition_fall 0.15691  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[3]}]
set_input_delay  1.111569 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[2]}]
set_input_delay  1.108317 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[2]}]
set_input_delay  1.067404 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[2]}]
set_input_delay  1.064116 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[2]}]
set_driving_cell -rise -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.137272  -input_transition_fall 0.074661  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[2]}]
set_driving_cell -fall -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.137272  -input_transition_fall 0.074661  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[2]}]
set_driving_cell -rise -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.137272  -input_transition_fall 0.074661  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[2]}]
set_driving_cell -fall -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.137272  -input_transition_fall 0.074661  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[2]}]
set_input_delay  1.08441 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[1]}]
set_input_delay  1.081154 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[1]}]
set_input_delay  1.042718 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[1]}]
set_input_delay  1.03943 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[1]}]
set_driving_cell -rise -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.143279  -input_transition_fall 0.077883  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[1]}]
set_driving_cell -fall -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.143279  -input_transition_fall 0.077883  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[1]}]
set_driving_cell -rise -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.143279  -input_transition_fall 0.077883  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[1]}]
set_driving_cell -fall -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.143279  -input_transition_fall 0.077883  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[1]}]
set_input_delay  1.110156 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[0]}]
set_input_delay  1.106905 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[0]}]
set_input_delay  1.06934 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[0]}]
set_input_delay  1.066047 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[0]}]
set_driving_cell -rise -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.143837  -input_transition_fall 0.078185  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[0]}]
set_driving_cell -fall -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.143837  -input_transition_fall 0.078185  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[0]}]
set_driving_cell -rise -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.143837  -input_transition_fall 0.078185  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[0]}]
set_driving_cell -fall -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.143837  -input_transition_fall 0.078185  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[0]}]
set_output_delay  0.063889 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_chip_select}]
set_output_delay  -0.223913 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_chip_select}]
set_output_delay  0.045681 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_chip_select}]
set_output_delay  -0.183242 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_chip_select}]
set_load -pin_load -max  0.001087 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_chip_select}]
set_load -pin_load -max  0.001087 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_chip_select}]
set_load -pin_load -min  0.001087 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_chip_select}]
set_load -pin_load -min  0.001087 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_chip_select}]
set_case_analysis 1 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3__Logic1_}]
set_case_analysis 0 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3__Logic0_}]
set_input_delay  1.107382 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[7]}]
set_input_delay  1.104141 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[7]}]
set_input_delay  1.060744 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[7]}]
set_input_delay  1.057484 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[7]}]
set_driving_cell -rise -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.148398  -input_transition_fall 0.080647  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[7]}]
set_driving_cell -fall -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.148398  -input_transition_fall 0.080647  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[7]}]
set_driving_cell -rise -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.148398  -input_transition_fall 0.080647  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[7]}]
set_driving_cell -fall -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.148398  -input_transition_fall 0.080647  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[7]}]
set_input_delay  1.088579 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[6]}]
set_input_delay  1.085335 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[6]}]
set_input_delay  1.045902 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[6]}]
set_input_delay  1.042649 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[6]}]
set_driving_cell -rise -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.135237  -input_transition_fall 0.073557  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[6]}]
set_driving_cell -fall -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.135237  -input_transition_fall 0.073557  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[6]}]
set_driving_cell -rise -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.135237  -input_transition_fall 0.073557  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[6]}]
set_driving_cell -fall -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.135237  -input_transition_fall 0.073557  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[6]}]
set_input_delay  1.112918 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[5]}]
set_input_delay  1.109683 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[5]}]
set_input_delay  1.066997 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[5]}]
set_input_delay  1.063722 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[5]}]
set_driving_cell -rise -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.14427  -input_transition_fall 0.078428  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[5]}]
set_driving_cell -fall -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.14427  -input_transition_fall 0.078428  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[5]}]
set_driving_cell -rise -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.14427  -input_transition_fall 0.078428  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[5]}]
set_driving_cell -fall -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.14427  -input_transition_fall 0.078428  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[5]}]
set_input_delay  0.977154 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[4]}]
set_input_delay  0.973904 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[4]}]
set_input_delay  0.978222 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[4]}]
set_input_delay  0.974972 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[4]}]
set_driving_cell -rise -max -library USERLIB_nldm_tt_1p00v_1p00v_25c -lib_cell sram_sp_hdc_svt_rvt_hvt -from_pin CLK -pin {Q[4]} -input_transition_rise 0.284194  -input_transition_fall 0.250073  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[4]}]
set_driving_cell -fall -max -library USERLIB_nldm_tt_1p00v_1p00v_25c -lib_cell sram_sp_hdc_svt_rvt_hvt -from_pin CLK -pin {Q[4]} -input_transition_rise 0.284194  -input_transition_fall 0.250073  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[4]}]
set_driving_cell -rise -min -library USERLIB_nldm_tt_1p00v_1p00v_25c -lib_cell sram_sp_hdc_svt_rvt_hvt -from_pin CLK -pin {Q[4]} -input_transition_rise 0.183991  -input_transition_fall 0.15691  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[4]}]
set_driving_cell -fall -min -library USERLIB_nldm_tt_1p00v_1p00v_25c -lib_cell sram_sp_hdc_svt_rvt_hvt -from_pin CLK -pin {Q[4]} -input_transition_rise 0.183991  -input_transition_fall 0.15691  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[4]}]
set_input_delay  1.108855 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[3]}]
set_input_delay  1.105617 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[3]}]
set_input_delay  1.063599 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[3]}]
set_input_delay  1.06033 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[3]}]
set_driving_cell -rise -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.144823  -input_transition_fall 0.07872  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[3]}]
set_driving_cell -fall -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.144823  -input_transition_fall 0.07872  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[3]}]
set_driving_cell -rise -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.144823  -input_transition_fall 0.07872  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[3]}]
set_driving_cell -fall -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.144823  -input_transition_fall 0.07872  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[3]}]
set_input_delay  1.125065 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[2]}]
set_input_delay  1.121831 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[2]}]
set_input_delay  1.075784 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[2]}]
set_input_delay  1.072506 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[2]}]
set_driving_cell -rise -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.140334  -input_transition_fall 0.076303  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[2]}]
set_driving_cell -fall -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.140334  -input_transition_fall 0.076303  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[2]}]
set_driving_cell -rise -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.140334  -input_transition_fall 0.076303  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[2]}]
set_driving_cell -fall -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.140334  -input_transition_fall 0.076303  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[2]}]
set_input_delay  1.103265 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[1]}]
set_input_delay  1.100033 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[1]}]
set_input_delay  1.062232 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[1]}]
set_input_delay  1.058957 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[1]}]
set_driving_cell -rise -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.138256  -input_transition_fall 0.07519  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[1]}]
set_driving_cell -fall -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.138256  -input_transition_fall 0.07519  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[1]}]
set_driving_cell -rise -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.138256  -input_transition_fall 0.07519  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[1]}]
set_driving_cell -fall -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.138256  -input_transition_fall 0.07519  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[1]}]
set_input_delay  1.119024 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[0]}]
set_input_delay  1.115788 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[0]}]
set_input_delay  1.074503 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[0]}]
set_input_delay  1.071228 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[0]}]
set_driving_cell -rise -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.143599  -input_transition_fall 0.078055  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[0]}]
set_driving_cell -fall -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.143599  -input_transition_fall 0.078055  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[0]}]
set_driving_cell -rise -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.143599  -input_transition_fall 0.078055  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[0]}]
set_driving_cell -fall -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.143599  -input_transition_fall 0.078055  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[0]}]
set_output_delay  0.079121 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_chip_select}]
set_output_delay  -0.209734 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_chip_select}]
set_output_delay  0.050761 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_chip_select}]
set_output_delay  -0.178184 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_chip_select}]
set_load -pin_load -max  0.002579 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_chip_select}]
set_load -pin_load -max  0.002579 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_chip_select}]
set_load -pin_load -min  0.002579 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_chip_select}]
set_load -pin_load -min  0.002579 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_chip_select}]
set_case_analysis 1 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2__Logic1_}]
set_case_analysis 0 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2__Logic0_}]
set_output_delay  -0.093626 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_n3}]
set_output_delay  -0.390464 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_n3}]
set_output_delay  -0.112756 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_n3}]
set_output_delay  -0.374671 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_n3}]
set_load -pin_load -max  0.006155 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_n3}]
set_load -pin_load -max  0.006155 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_n3}]
set_load -pin_load -min  0.006155 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_n3}]
set_load -pin_load -min  0.006155 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_n3}]
set_output_delay  -0.097321 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_n2}]
set_output_delay  -0.394911 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_n2}]
set_output_delay  -0.114966 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_n2}]
set_output_delay  -0.377869 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_n2}]
set_load -pin_load -max  0.006155 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_n2}]
set_load -pin_load -max  0.006155 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_n2}]
set_load -pin_load -min  0.006155 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_n2}]
set_load -pin_load -min  0.006155 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_n2}]
set_output_delay  0.009084 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[31]}]
set_output_delay  -0.200936 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[31]}]
set_output_delay  0.007155 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[31]}]
set_output_delay  -0.22831 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[31]}]
set_load -pin_load -max  0.001506 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[31]}]
set_load -pin_load -max  0.001506 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[31]}]
set_load -pin_load -min  0.001506 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[31]}]
set_load -pin_load -min  0.001506 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[31]}]
set_output_delay  0.036414 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[30]}]
set_output_delay  -0.173564 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[30]}]
set_output_delay  0.015942 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[30]}]
set_output_delay  -0.21959 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[30]}]
set_load -pin_load -max  0.001037 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[30]}]
set_load -pin_load -max  0.001037 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[30]}]
set_load -pin_load -min  0.001037 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[30]}]
set_load -pin_load -min  0.001037 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[30]}]
set_output_delay  0.052929 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[29]}]
set_output_delay  -0.156792 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[29]}]
set_output_delay  0.042416 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[29]}]
set_output_delay  -0.19263 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[29]}]
set_load -pin_load -max  0.001506 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[29]}]
set_load -pin_load -max  0.001506 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[29]}]
set_load -pin_load -min  0.001506 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[29]}]
set_load -pin_load -min  0.001506 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[29]}]
set_output_delay  0.045173 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[28]}]
set_output_delay  -0.164626 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[28]}]
set_output_delay  0.027943 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[28]}]
set_output_delay  -0.207251 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[28]}]
set_load -pin_load -max  0.00254 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[28]}]
set_load -pin_load -max  0.00254 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[28]}]
set_load -pin_load -min  0.00254 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[28]}]
set_load -pin_load -min  0.00254 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[28]}]
set_output_delay  0.03582 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[27]}]
set_output_delay  -0.173801 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[27]}]
set_output_delay  0.031028 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[27]}]
set_output_delay  -0.203829 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[27]}]
set_load -pin_load -max  0.001424 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[27]}]
set_load -pin_load -max  0.001424 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[27]}]
set_load -pin_load -min  0.001424 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[27]}]
set_load -pin_load -min  0.001424 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[27]}]
set_output_delay  0.064124 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[26]}]
set_output_delay  -0.145071 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[26]}]
set_output_delay  0.074995 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[26]}]
set_output_delay  -0.159074 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[26]}]
set_load -pin_load -max  0.001424 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[26]}]
set_load -pin_load -max  0.001424 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[26]}]
set_load -pin_load -min  0.001424 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[26]}]
set_load -pin_load -min  0.001424 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[26]}]
set_output_delay  0.046116 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[25]}]
set_output_delay  -0.16336 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[25]}]
set_output_delay  0.046636 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[25]}]
set_output_delay  -0.187943 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[25]}]
set_load -pin_load -max  0.001424 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[25]}]
set_load -pin_load -max  0.001424 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[25]}]
set_load -pin_load -min  0.001424 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[25]}]
set_load -pin_load -min  0.001424 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[25]}]
set_output_delay  0.048756 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[24]}]
set_output_delay  -0.160659 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[24]}]
set_output_delay  0.051543 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[24]}]
set_output_delay  -0.182923 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[24]}]
set_load -pin_load -max  0.001424 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[24]}]
set_load -pin_load -max  0.001424 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[24]}]
set_load -pin_load -min  0.001424 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[24]}]
set_load -pin_load -min  0.001424 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[24]}]
set_output_delay  0.067731 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[23]}]
set_output_delay  -0.142267 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[23]}]
set_output_delay  0.037274 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[23]}]
set_output_delay  -0.198322 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[23]}]
set_load -pin_load -max  0.001424 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[23]}]
set_load -pin_load -max  0.001424 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[23]}]
set_load -pin_load -min  0.001424 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[23]}]
set_load -pin_load -min  0.001424 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[23]}]
set_output_delay  0.041294 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[22]}]
set_output_delay  -0.168626 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[22]}]
set_output_delay  0.021239 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[22]}]
set_output_delay  -0.214212 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[22]}]
set_load -pin_load -max  0.001037 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[22]}]
set_load -pin_load -max  0.001037 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[22]}]
set_load -pin_load -min  0.001037 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[22]}]
set_load -pin_load -min  0.001037 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[22]}]
set_output_delay  0.038197 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[21]}]
set_output_delay  -0.171611 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[21]}]
set_output_delay  0.024231 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[21]}]
set_output_delay  -0.211009 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[21]}]
set_load -pin_load -max  0.002717 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[21]}]
set_load -pin_load -max  0.002717 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[21]}]
set_load -pin_load -min  0.002717 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[21]}]
set_load -pin_load -min  0.002717 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[21]}]
set_output_delay  0.043152 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[20]}]
set_output_delay  -0.166608 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[20]}]
set_output_delay  0.029488 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[20]}]
set_output_delay  -0.205661 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[20]}]
set_load -pin_load -max  0.001506 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[20]}]
set_load -pin_load -max  0.001506 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[20]}]
set_load -pin_load -min  0.001506 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[20]}]
set_load -pin_load -min  0.001506 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[20]}]
set_output_delay  -0.098802 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[19]}]
set_output_delay  -0.308754 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[19]}]
set_output_delay  -0.10808 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[19]}]
set_output_delay  -0.343872 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[19]}]
set_load -pin_load -max  0.001537 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[19]}]
set_load -pin_load -max  0.001537 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[19]}]
set_load -pin_load -min  0.001537 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[19]}]
set_load -pin_load -min  0.001537 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[19]}]
set_output_delay  0.034834 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[18]}]
set_output_delay  -0.174678 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[18]}]
set_output_delay  0.033101 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[18]}]
set_output_delay  -0.201575 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[18]}]
set_load -pin_load -max  0.001424 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[18]}]
set_load -pin_load -max  0.001424 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[18]}]
set_load -pin_load -min  0.001424 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[18]}]
set_load -pin_load -min  0.001424 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[18]}]
set_output_delay  0.048306 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[17]}]
set_output_delay  -0.161106 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[17]}]
set_output_delay  0.050002 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[17]}]
set_output_delay  -0.184487 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[17]}]
set_load -pin_load -max  0.001424 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[17]}]
set_load -pin_load -max  0.001424 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[17]}]
set_load -pin_load -min  0.001424 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[17]}]
set_load -pin_load -min  0.001424 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[17]}]
set_output_delay  0.057677 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[16]}]
set_output_delay  -0.151695 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[16]}]
set_output_delay  0.060724 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[16]}]
set_output_delay  -0.173691 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[16]}]
set_load -pin_load -max  0.001424 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[16]}]
set_load -pin_load -max  0.001424 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[16]}]
set_load -pin_load -min  0.001424 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[16]}]
set_load -pin_load -min  0.001424 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[16]}]
set_output_delay  0.188444 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[11]}]
set_output_delay  -0.368887 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[11]}]
set_output_delay  0.161574 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[11]}]
set_output_delay  -0.330332 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[11]}]
set_load -pin_load -max  0.006633 [get_ports {u_ahb_ram_genblk3_SRAMADDR[11]}]
set_load -pin_load -max  0.006633 [get_ports {u_ahb_ram_genblk3_SRAMADDR[11]}]
set_load -pin_load -min  0.006633 [get_ports {u_ahb_ram_genblk3_SRAMADDR[11]}]
set_load -pin_load -min  0.006633 [get_ports {u_ahb_ram_genblk3_SRAMADDR[11]}]
set_output_delay  0.179783 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[10]}]
set_output_delay  -0.213799 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[10]}]
set_output_delay  0.164491 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[10]}]
set_output_delay  -0.161018 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[10]}]
set_load -pin_load -max  0.00293 [get_ports {u_ahb_ram_genblk3_SRAMADDR[10]}]
set_load -pin_load -max  0.00293 [get_ports {u_ahb_ram_genblk3_SRAMADDR[10]}]
set_load -pin_load -min  0.00293 [get_ports {u_ahb_ram_genblk3_SRAMADDR[10]}]
set_load -pin_load -min  0.00293 [get_ports {u_ahb_ram_genblk3_SRAMADDR[10]}]
set_output_delay  0.171142 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[9]}]
set_output_delay  -0.373684 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[9]}]
set_output_delay  0.161659 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[9]}]
set_output_delay  -0.333002 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[9]}]
set_load -pin_load -max  0.007052 [get_ports {u_ahb_ram_genblk3_SRAMADDR[9]}]
set_load -pin_load -max  0.007052 [get_ports {u_ahb_ram_genblk3_SRAMADDR[9]}]
set_load -pin_load -min  0.007052 [get_ports {u_ahb_ram_genblk3_SRAMADDR[9]}]
set_load -pin_load -min  0.007052 [get_ports {u_ahb_ram_genblk3_SRAMADDR[9]}]
set_output_delay  0.172441 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[8]}]
set_output_delay  -0.366523 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[8]}]
set_output_delay  0.170024 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[8]}]
set_output_delay  -0.328132 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[8]}]
set_load -pin_load -max  0.00697 [get_ports {u_ahb_ram_genblk3_SRAMADDR[8]}]
set_load -pin_load -max  0.00697 [get_ports {u_ahb_ram_genblk3_SRAMADDR[8]}]
set_load -pin_load -min  0.00697 [get_ports {u_ahb_ram_genblk3_SRAMADDR[8]}]
set_load -pin_load -min  0.00697 [get_ports {u_ahb_ram_genblk3_SRAMADDR[8]}]
set_output_delay  0.155387 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[7]}]
set_output_delay  -0.371707 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[7]}]
set_output_delay  0.147073 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[7]}]
set_output_delay  -0.331356 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[7]}]
set_load -pin_load -max  0.00697 [get_ports {u_ahb_ram_genblk3_SRAMADDR[7]}]
set_load -pin_load -max  0.00697 [get_ports {u_ahb_ram_genblk3_SRAMADDR[7]}]
set_load -pin_load -min  0.00697 [get_ports {u_ahb_ram_genblk3_SRAMADDR[7]}]
set_load -pin_load -min  0.00697 [get_ports {u_ahb_ram_genblk3_SRAMADDR[7]}]
set_output_delay  0.169579 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[6]}]
set_output_delay  -0.368903 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[6]}]
set_output_delay  0.160153 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[6]}]
set_output_delay  -0.330155 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[6]}]
set_load -pin_load -max  0.00697 [get_ports {u_ahb_ram_genblk3_SRAMADDR[6]}]
set_load -pin_load -max  0.00697 [get_ports {u_ahb_ram_genblk3_SRAMADDR[6]}]
set_load -pin_load -min  0.00697 [get_ports {u_ahb_ram_genblk3_SRAMADDR[6]}]
set_load -pin_load -min  0.00697 [get_ports {u_ahb_ram_genblk3_SRAMADDR[6]}]
set_output_delay  0.178861 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[5]}]
set_output_delay  -0.364289 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[5]}]
set_output_delay  0.177191 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[5]}]
set_output_delay  -0.326351 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[5]}]
set_load -pin_load -max  0.00697 [get_ports {u_ahb_ram_genblk3_SRAMADDR[5]}]
set_load -pin_load -max  0.00697 [get_ports {u_ahb_ram_genblk3_SRAMADDR[5]}]
set_load -pin_load -min  0.00697 [get_ports {u_ahb_ram_genblk3_SRAMADDR[5]}]
set_load -pin_load -min  0.00697 [get_ports {u_ahb_ram_genblk3_SRAMADDR[5]}]
set_output_delay  0.180492 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[4]}]
set_output_delay  -0.219416 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[4]}]
set_output_delay  0.165165 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[4]}]
set_output_delay  -0.168847 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[4]}]
set_load -pin_load -max  0.002593 [get_ports {u_ahb_ram_genblk3_SRAMADDR[4]}]
set_load -pin_load -max  0.002593 [get_ports {u_ahb_ram_genblk3_SRAMADDR[4]}]
set_load -pin_load -min  0.002593 [get_ports {u_ahb_ram_genblk3_SRAMADDR[4]}]
set_load -pin_load -min  0.002593 [get_ports {u_ahb_ram_genblk3_SRAMADDR[4]}]
set_output_delay  0.170304 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[3]}]
set_output_delay  -0.372966 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[3]}]
set_output_delay  0.159786 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[3]}]
set_output_delay  -0.33262 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[3]}]
set_load -pin_load -max  0.007052 [get_ports {u_ahb_ram_genblk3_SRAMADDR[3]}]
set_load -pin_load -max  0.007052 [get_ports {u_ahb_ram_genblk3_SRAMADDR[3]}]
set_load -pin_load -min  0.007052 [get_ports {u_ahb_ram_genblk3_SRAMADDR[3]}]
set_load -pin_load -min  0.007052 [get_ports {u_ahb_ram_genblk3_SRAMADDR[3]}]
set_output_delay  0.161576 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[2]}]
set_output_delay  -0.372479 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[2]}]
set_output_delay  0.155458 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[2]}]
set_output_delay  -0.332166 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[2]}]
set_load -pin_load -max  0.007052 [get_ports {u_ahb_ram_genblk3_SRAMADDR[2]}]
set_load -pin_load -max  0.007052 [get_ports {u_ahb_ram_genblk3_SRAMADDR[2]}]
set_load -pin_load -min  0.007052 [get_ports {u_ahb_ram_genblk3_SRAMADDR[2]}]
set_load -pin_load -min  0.007052 [get_ports {u_ahb_ram_genblk3_SRAMADDR[2]}]
set_output_delay  0.163385 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[1]}]
set_output_delay  -0.365891 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[1]}]
set_output_delay  0.149849 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[1]}]
set_output_delay  -0.327747 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[1]}]
set_load -pin_load -max  0.007052 [get_ports {u_ahb_ram_genblk3_SRAMADDR[1]}]
set_load -pin_load -max  0.007052 [get_ports {u_ahb_ram_genblk3_SRAMADDR[1]}]
set_load -pin_load -min  0.007052 [get_ports {u_ahb_ram_genblk3_SRAMADDR[1]}]
set_load -pin_load -min  0.007052 [get_ports {u_ahb_ram_genblk3_SRAMADDR[1]}]
set_output_delay  0.175479 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[0]}]
set_output_delay  -0.366851 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[0]}]
set_output_delay  0.158837 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[0]}]
set_output_delay  -0.328529 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[0]}]
set_load -pin_load -max  0.007052 [get_ports {u_ahb_ram_genblk3_SRAMADDR[0]}]
set_load -pin_load -max  0.007052 [get_ports {u_ahb_ram_genblk3_SRAMADDR[0]}]
set_load -pin_load -min  0.007052 [get_ports {u_ahb_ram_genblk3_SRAMADDR[0]}]
set_load -pin_load -min  0.007052 [get_ports {u_ahb_ram_genblk3_SRAMADDR[0]}]
set_load -pin_load -max  0.061808 [get_ports {gated_hclk}]
set_load -pin_load -max  0.061808 [get_ports {gated_hclk}]
set_load -pin_load -min  0.061808 [get_ports {gated_hclk}]
set_load -pin_load -min  0.061808 [get_ports {gated_hclk}]
set_clock_latency -source -rise -late  -clock [get_clocks {XTAL1}]  0.001035 [get_ports {XTAL1}]
set_clock_latency -source -rise -early  -clock [get_clocks {XTAL1}]  0.000586 [get_ports {XTAL1}]
set_clock_latency -source -fall -late  -clock [get_clocks {XTAL1}]  0.001035 [get_ports {XTAL1}]
set_clock_latency -source -fall -early  -clock [get_clocks {XTAL1}]  0.000586 [get_ports {XTAL1}]
set_propagated_clock [get_pins {u_cmsdk_mcu_clkctrl/U3/B}]
set_propagated_clock [get_pins {CTS_cdb_BUF_PCLK_G0_L1_2/A}]
set_propagated_clock [get_pins {CTS_ccd_BUF_PCLK_G0_L1_1/A}]
set_input_delay  0.378724 -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {SWDIOTMS}]
set_input_delay  0.452768 -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {SWDIOTMS}]
set_input_delay  0.002602 -min -add_delay -network_latency_included -source_latency_included [get_ports {SWDIOTMS}]
set_input_delay  0.00833 -max -add_delay -network_latency_included -source_latency_included [get_ports {SWCLKTCK}]
set_input_delay  0.007404 -min -add_delay -network_latency_included -source_latency_included [get_ports {SWCLKTCK}]
set_input_delay  0.401662 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {P1[15]}]
set_input_delay  0.329294 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {P1[15]}]
set_input_delay  0.421474 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {P1[15]}]
set_input_delay  0.320769 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {P1[15]}]
set_input_delay  0.000411 -add_delay -network_latency_included -source_latency_included [get_ports {P1[15]}]
set_input_delay  0.414773 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {P1[14]}]
set_input_delay  0.328352 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {P1[14]}]
set_input_delay  0.449375 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {P1[14]}]
set_input_delay  0.319881 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {P1[14]}]
set_input_delay  0.000962 -add_delay -network_latency_included -source_latency_included [get_ports {P1[14]}]
set_input_delay  0.4134 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {P1[13]}]
set_input_delay  0.327398 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {P1[13]}]
set_input_delay  0.446284 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {P1[13]}]
set_input_delay  0.318903 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {P1[13]}]
set_input_delay  0.002037 -add_delay -network_latency_included -source_latency_included [get_ports {P1[13]}]
set_input_delay  0.389091 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {P1[12]}]
set_input_delay  0.328718 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {P1[12]}]
set_input_delay  0.401484 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {P1[12]}]
set_input_delay  0.320206 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {P1[12]}]
set_input_delay  0.000321 -add_delay -network_latency_included -source_latency_included [get_ports {P1[12]}]
set_input_delay  0.38371 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {P1[11]}]
set_input_delay  0.328903 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {P1[11]}]
set_input_delay  0.393404 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {P1[11]}]
set_input_delay  0.320422 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {P1[11]}]
set_input_delay  0.000403 -add_delay -network_latency_included -source_latency_included [get_ports {P1[11]}]
set_input_delay  0.388762 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {P1[10]}]
set_input_delay  0.327614 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {P1[10]}]
set_input_delay  0.402388 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {P1[10]}]
set_input_delay  0.319133 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {P1[10]}]
set_input_delay  0.000413 -add_delay -network_latency_included -source_latency_included [get_ports {P1[10]}]
set_input_delay  0.415752 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {P1[9]}]
set_input_delay  0.33082 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {P1[9]}]
set_input_delay  0.444588 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {P1[9]}]
set_input_delay  0.322306 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {P1[9]}]
set_input_delay  0.000917 -max -add_delay -network_latency_included -source_latency_included [get_ports {P1[9]}]
set_input_delay  0.000527 -min -add_delay -network_latency_included -source_latency_included [get_ports {P1[9]}]
set_input_delay  0.002542 -max -add_delay -network_latency_included -source_latency_included [get_ports {P1[8]}]
set_input_delay  0.002309 -min -add_delay -network_latency_included -source_latency_included [get_ports {P1[8]}]
set_input_delay  0.393462 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {P1[8]}]
set_input_delay  0.306294 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {P1[8]}]
set_input_delay  0.424392 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {P1[8]}]
set_input_delay  0.297773 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {P1[8]}]
set_input_delay  0.362689 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {P1[7]}]
set_input_delay  0.304551 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {P1[7]}]
set_input_delay  0.38094 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {P1[7]}]
set_input_delay  0.296088 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {P1[7]}]
set_input_delay  0.00037 -add_delay -network_latency_included -source_latency_included [get_ports {P1[7]}]
set_input_delay  0.402069 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {P1[6]}]
set_input_delay  0.305767 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {P1[6]}]
set_input_delay  0.446247 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {P1[6]}]
set_input_delay  0.297278 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {P1[6]}]
set_input_delay  0.002197 -add_delay -network_latency_included -source_latency_included [get_ports {P1[6]}]
set_input_delay  0.48422 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {P1[5]}]
set_input_delay  0.3354 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {P1[5]}]
set_input_delay  0.491674 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {P1[5]}]
set_input_delay  0.327085 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {P1[5]}]
set_input_delay  0.000366 -add_delay -network_latency_included -source_latency_included [get_ports {P1[5]}]
set_input_delay  0.422157 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {P1[4]}]
set_input_delay  0.304791 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {P1[4]}]
set_input_delay  0.486087 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {P1[4]}]
set_input_delay  0.296321 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {P1[4]}]
set_input_delay  0.004105 -max -add_delay -network_latency_included -source_latency_included [get_ports {P1[4]}]
set_input_delay  0.003431 -min -add_delay -network_latency_included -source_latency_included [get_ports {P1[4]}]
set_input_delay  0.489317 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {P1[3]}]
set_input_delay  0.336728 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {P1[3]}]
set_input_delay  0.49485 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {P1[3]}]
set_input_delay  0.3284 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {P1[3]}]
set_input_delay  0.000373 -add_delay -network_latency_included -source_latency_included [get_ports {P1[3]}]
set_input_delay  0.398872 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {P1[2]}]
set_input_delay  0.308503 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {P1[2]}]
set_input_delay  0.433987 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {P1[2]}]
set_input_delay  0.299967 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {P1[2]}]
set_input_delay  0.001808 -max -add_delay -network_latency_included -source_latency_included [get_ports {P1[2]}]
set_input_delay  0.001364 -min -add_delay -network_latency_included -source_latency_included [get_ports {P1[2]}]
set_input_delay  0.505796 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {P1[1]}]
set_input_delay  0.336803 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {P1[1]}]
set_input_delay  0.516298 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {P1[1]}]
set_input_delay  0.32846 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {P1[1]}]
set_input_delay  0.000979 -add_delay -network_latency_included -source_latency_included [get_ports {P1[1]}]
set_input_delay  0.398015 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {P1[0]}]
set_input_delay  0.306103 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {P1[0]}]
set_input_delay  0.440632 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {P1[0]}]
set_input_delay  0.297609 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {P1[0]}]
set_input_delay  0.00438 -max -add_delay -network_latency_included -source_latency_included [get_ports {P1[0]}]
set_input_delay  0.00374 -min -add_delay -network_latency_included -source_latency_included [get_ports {P1[0]}]
set_input_delay  0.398633 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {P0[15]}]
set_input_delay  0.335828 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {P0[15]}]
set_input_delay  0.410331 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {P0[15]}]
set_input_delay  0.327226 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {P0[15]}]
set_input_delay  0.000721 -add_delay -network_latency_included -source_latency_included [get_ports {P0[15]}]
set_input_delay  0.390563 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {P0[14]}]
set_input_delay  0.331098 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {P0[14]}]
set_input_delay  0.403028 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {P0[14]}]
set_input_delay  0.32261 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {P0[14]}]
set_input_delay  0.000838 -add_delay -network_latency_included -source_latency_included [get_ports {P0[14]}]
set_input_delay  0.407489 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {P0[13]}]
set_input_delay  0.330453 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {P0[13]}]
set_input_delay  0.434355 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {P0[13]}]
set_input_delay  0.321974 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {P0[13]}]
set_input_delay  0.001694 -add_delay -network_latency_included -source_latency_included [get_ports {P0[13]}]
set_input_delay  0.41332 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {P0[12]}]
set_input_delay  0.333351 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {P0[12]}]
set_input_delay  0.438265 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {P0[12]}]
set_input_delay  0.324799 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {P0[12]}]
set_input_delay  0.001445 -add_delay -network_latency_included -source_latency_included [get_ports {P0[12]}]
set_input_delay  0.392535 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {P0[11]}]
set_input_delay  0.328594 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {P0[11]}]
set_input_delay  0.40841 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {P0[11]}]
set_input_delay  0.320127 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {P0[11]}]
set_input_delay  0.001162 -add_delay -network_latency_included -source_latency_included [get_ports {P0[11]}]
set_input_delay  0.417263 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {P0[10]}]
set_input_delay  0.328504 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {P0[10]}]
set_input_delay  0.454301 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {P0[10]}]
set_input_delay  0.320037 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {P0[10]}]
set_input_delay  0.00104 -add_delay -network_latency_included -source_latency_included [get_ports {P0[10]}]
set_input_delay  0.411191 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {P0[9]}]
set_input_delay  0.337789 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {P0[9]}]
set_input_delay  0.428532 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {P0[9]}]
set_input_delay  0.329146 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {P0[9]}]
set_input_delay  0.001066 -add_delay -network_latency_included -source_latency_included [get_ports {P0[9]}]
set_input_delay  0.384257 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {P0[8]}]
set_input_delay  0.333694 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {P0[8]}]
set_input_delay  0.389867 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {P0[8]}]
set_input_delay  0.325155 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {P0[8]}]
set_input_delay  0.000296 -add_delay -network_latency_included -source_latency_included [get_ports {P0[8]}]
set_input_delay  0.39383 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {P0[7]}]
set_input_delay  0.315667 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {P0[7]}]
set_input_delay  0.427675 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {P0[7]}]
set_input_delay  0.307199 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {P0[7]}]
set_input_delay  0.001064 -add_delay -network_latency_included -source_latency_included [get_ports {P0[7]}]
set_input_delay  0.398492 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {P0[6]}]
set_input_delay  0.330552 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {P0[6]}]
set_input_delay  0.419731 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {P0[6]}]
set_input_delay  0.322067 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {P0[6]}]
set_input_delay  0.000433 -add_delay -network_latency_included -source_latency_included [get_ports {P0[6]}]
set_input_delay  0.389351 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {P0[5]}]
set_input_delay  0.328611 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {P0[5]}]
set_input_delay  0.416598 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {P0[5]}]
set_input_delay  0.320147 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {P0[5]}]
set_input_delay  0.00071 -add_delay -network_latency_included -source_latency_included [get_ports {P0[5]}]
set_input_delay  0.393342 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {P0[4]}]
set_input_delay  0.31546 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {P0[4]}]
set_input_delay  0.428497 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {P0[4]}]
set_input_delay  0.307001 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {P0[4]}]
set_input_delay  0.001375 -add_delay -network_latency_included -source_latency_included [get_ports {P0[4]}]
set_input_delay  0.401267 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {P0[3]}]
set_input_delay  0.316648 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {P0[3]}]
set_input_delay  0.440562 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {P0[3]}]
set_input_delay  0.308164 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {P0[3]}]
set_input_delay  0.002011 -add_delay -network_latency_included -source_latency_included [get_ports {P0[3]}]
set_input_delay  0.396091 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {P0[2]}]
set_input_delay  0.315894 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {P0[2]}]
set_input_delay  0.433536 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {P0[2]}]
set_input_delay  0.307423 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {P0[2]}]
set_input_delay  0.001823 -add_delay -network_latency_included -source_latency_included [get_ports {P0[2]}]
set_input_delay  0.379958 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {P0[1]}]
set_input_delay  0.31635 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {P0[1]}]
set_input_delay  0.399366 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {P0[1]}]
set_input_delay  0.307873 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {P0[1]}]
set_input_delay  0.000759 -add_delay -network_latency_included -source_latency_included [get_ports {P0[1]}]
set_input_delay  0.408239 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {P0[0]}]
set_input_delay  0.314709 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {P0[0]}]
set_input_delay  0.45819 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {P0[0]}]
set_input_delay  0.30626 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {P0[0]}]
set_input_delay  0.001558 -add_delay -network_latency_included -source_latency_included [get_ports {P0[0]}]
set_input_delay  0.000861 -add_delay -network_latency_included -source_latency_included [get_ports {NRST}]
###############################################################################
# Extra setting
###############################################################################
set timing_input_port_default_clock false
set auto_wire_load_selection false
set_wire_load_mode top
###############################################################################
# POCV Information
###############################################################################
