###############################################################################
#
# Created by PrimeTime on Wed Aug 26 17:45:21 2020
#
###############################################################################
# 
# Written by HyperScale Constraint Extractor
# Version : M-2017.06-SP1
# Top design name : cmsdk_mcu
# Block name : PARTMAIN
# Extraction Mode : normal
# Instance : u_core_context/u_part_main
# 
###############################################################################
set_units -time ns -capacitance pF -current mA -voltage V -resistance kOhm -power pW
###############################################################################
#  
# Units
# capacitive_load_unit           : 1 pF
# current_unit                   : 0.001 A
# resistance_unit                : 1 kOhm
# time_unit                      : 1 ns
# voltage_unit                   : 1 V
###############################################################################
set_operating_conditions -analysis_type on_chip_variation  -library [get_libs {scadv10_cln65gp_rvt_tt_1p0v_25c.db:scadv10_cln65gp_rvt_tt_1p0v_25c}] 
create_clock -name XTAL1 -period 2.5 -waveform { 0 1.25 } -add [get_ports {XTAL1}]
###############################################################################
#
# Created by pt_shell on Wed Aug 26 17:45:21 2020
#
###############################################################################
# 
# Written by HyperScale Constraint Extractor
# Version : M-2017.06-SP1
# Top design name : cmsdk_mcu
# Block name : PARTMAIN
# Extraction Mode : normal
# Instance : u_core_context/u_part_main
# 
###############################################################################
set_clock_map XTAL1 -parent_clock XTAL1
###############################################################################
# Boundary Context Information
###############################################################################
set_max_capacitance  0.75 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[7]}]
set_max_transition  1 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[7]}]
set_max_capacitance  0.75 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[6]}]
set_max_transition  1 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[6]}]
set_max_capacitance  0.75 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[5]}]
set_max_transition  1 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[5]}]
set_max_capacitance  0.75 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[4]}]
set_max_transition  1 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[4]}]
set_max_capacitance  0.75 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[3]}]
set_max_transition  1 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[3]}]
set_max_capacitance  0.75 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[2]}]
set_max_transition  1 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[2]}]
set_max_capacitance  0.75 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[1]}]
set_max_transition  1 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[1]}]
set_max_capacitance  0.75 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[0]}]
set_max_transition  1 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[0]}]
set_max_capacitance  0.75 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[7]}]
set_max_transition  1 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[7]}]
set_max_capacitance  0.75 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[6]}]
set_max_transition  1 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[6]}]
set_max_capacitance  0.75 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[5]}]
set_max_transition  1 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[5]}]
set_max_capacitance  0.75 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[4]}]
set_max_transition  1 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[4]}]
set_max_capacitance  0.75 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[3]}]
set_max_transition  1 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[3]}]
set_max_capacitance  0.75 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[2]}]
set_max_transition  1 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[2]}]
set_max_capacitance  0.75 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[1]}]
set_max_transition  1 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[1]}]
set_max_capacitance  0.75 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[0]}]
set_max_transition  1 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[0]}]
set_max_transition  1 [get_ports {u_ahb_ram_genblk3_SRAMADDR[11]}]
set_max_transition  1 [get_ports {u_ahb_ram_genblk3_SRAMADDR[10]}]
set_max_transition  1 [get_ports {u_ahb_ram_genblk3_SRAMADDR[9]}]
set_max_transition  1 [get_ports {u_ahb_ram_genblk3_SRAMADDR[8]}]
set_max_transition  1 [get_ports {u_ahb_ram_genblk3_SRAMADDR[4]}]
set_max_transition  1 [get_ports {u_ahb_ram_genblk3_SRAMADDR[3]}]
set_max_transition  1 [get_ports {u_ahb_ram_genblk3_SRAMADDR[0]}]
set_driving_cell -rise -max -library USERLIB_nldm_tt_1p00v_1p00v_25c -lib_cell sram_sp_hdc_svt_rvt_hvt -from_pin CLK -pin {Q[7]} -input_transition_rise 0.190491  -input_transition_fall 0.174569  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[7]}]
set_driving_cell -fall -max -library USERLIB_nldm_tt_1p00v_1p00v_25c -lib_cell sram_sp_hdc_svt_rvt_hvt -from_pin CLK -pin {Q[7]} -input_transition_rise 0.190491  -input_transition_fall 0.174569  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[7]}]
set_driving_cell -rise -min -library USERLIB_nldm_tt_1p00v_1p00v_25c -lib_cell sram_sp_hdc_svt_rvt_hvt -from_pin CLK -pin {Q[7]} -input_transition_rise 0.105968  -input_transition_fall 0.090437  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[7]}]
set_driving_cell -fall -min -library USERLIB_nldm_tt_1p00v_1p00v_25c -lib_cell sram_sp_hdc_svt_rvt_hvt -from_pin CLK -pin {Q[7]} -input_transition_rise 0.105968  -input_transition_fall 0.090437  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[7]}]
set_input_delay  0.883301 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[7]}]
set_input_delay  0.880559 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[7]}]
set_input_delay  0.879326 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[7]}]
set_input_delay  0.876584 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[7]}]
set_driving_cell -rise -max -library USERLIB_nldm_tt_1p00v_1p00v_25c -lib_cell sram_sp_hdc_svt_rvt_hvt -from_pin CLK -pin {Q[6]} -input_transition_rise 0.190491  -input_transition_fall 0.174569  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[6]}]
set_driving_cell -fall -max -library USERLIB_nldm_tt_1p00v_1p00v_25c -lib_cell sram_sp_hdc_svt_rvt_hvt -from_pin CLK -pin {Q[6]} -input_transition_rise 0.190491  -input_transition_fall 0.174569  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[6]}]
set_driving_cell -rise -min -library USERLIB_nldm_tt_1p00v_1p00v_25c -lib_cell sram_sp_hdc_svt_rvt_hvt -from_pin CLK -pin {Q[6]} -input_transition_rise 0.105968  -input_transition_fall 0.090437  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[6]}]
set_driving_cell -fall -min -library USERLIB_nldm_tt_1p00v_1p00v_25c -lib_cell sram_sp_hdc_svt_rvt_hvt -from_pin CLK -pin {Q[6]} -input_transition_rise 0.105968  -input_transition_fall 0.090437  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[6]}]
set_input_delay  0.894301 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[6]}]
set_input_delay  0.891559 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[6]}]
set_input_delay  0.895105 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[6]}]
set_input_delay  0.892362 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[6]}]
set_driving_cell -rise -max -library USERLIB_nldm_tt_1p00v_1p00v_25c -lib_cell sram_sp_hdc_svt_rvt_hvt -from_pin CLK -pin {Q[5]} -input_transition_rise 0.190491  -input_transition_fall 0.174569  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[5]}]
set_driving_cell -fall -max -library USERLIB_nldm_tt_1p00v_1p00v_25c -lib_cell sram_sp_hdc_svt_rvt_hvt -from_pin CLK -pin {Q[5]} -input_transition_rise 0.190491  -input_transition_fall 0.174569  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[5]}]
set_driving_cell -rise -min -library USERLIB_nldm_tt_1p00v_1p00v_25c -lib_cell sram_sp_hdc_svt_rvt_hvt -from_pin CLK -pin {Q[5]} -input_transition_rise 0.105968  -input_transition_fall 0.090437  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[5]}]
set_driving_cell -fall -min -library USERLIB_nldm_tt_1p00v_1p00v_25c -lib_cell sram_sp_hdc_svt_rvt_hvt -from_pin CLK -pin {Q[5]} -input_transition_rise 0.105968  -input_transition_fall 0.090437  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[5]}]
set_input_delay  0.885268 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[5]}]
set_input_delay  0.882526 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[5]}]
set_input_delay  0.882549 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[5]}]
set_input_delay  0.879807 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[5]}]
set_driving_cell -rise -max -library USERLIB_nldm_tt_1p00v_1p00v_25c -lib_cell sram_sp_hdc_svt_rvt_hvt -from_pin CLK -pin {Q[4]} -input_transition_rise 0.190491  -input_transition_fall 0.174569  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[4]}]
set_driving_cell -fall -max -library USERLIB_nldm_tt_1p00v_1p00v_25c -lib_cell sram_sp_hdc_svt_rvt_hvt -from_pin CLK -pin {Q[4]} -input_transition_rise 0.190491  -input_transition_fall 0.174569  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[4]}]
set_driving_cell -rise -min -library USERLIB_nldm_tt_1p00v_1p00v_25c -lib_cell sram_sp_hdc_svt_rvt_hvt -from_pin CLK -pin {Q[4]} -input_transition_rise 0.105968  -input_transition_fall 0.090437  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[4]}]
set_driving_cell -fall -min -library USERLIB_nldm_tt_1p00v_1p00v_25c -lib_cell sram_sp_hdc_svt_rvt_hvt -from_pin CLK -pin {Q[4]} -input_transition_rise 0.105968  -input_transition_fall 0.090437  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[4]}]
set_input_delay  0.887554 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[4]}]
set_input_delay  0.884812 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[4]}]
set_input_delay  0.885275 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[4]}]
set_input_delay  0.882533 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[4]}]
set_driving_cell -rise -max -library USERLIB_nldm_tt_1p00v_1p00v_25c -lib_cell sram_sp_hdc_svt_rvt_hvt -from_pin CLK -pin {Q[3]} -input_transition_rise 0.190491  -input_transition_fall 0.174569  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[3]}]
set_driving_cell -fall -max -library USERLIB_nldm_tt_1p00v_1p00v_25c -lib_cell sram_sp_hdc_svt_rvt_hvt -from_pin CLK -pin {Q[3]} -input_transition_rise 0.190491  -input_transition_fall 0.174569  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[3]}]
set_driving_cell -rise -min -library USERLIB_nldm_tt_1p00v_1p00v_25c -lib_cell sram_sp_hdc_svt_rvt_hvt -from_pin CLK -pin {Q[3]} -input_transition_rise 0.105968  -input_transition_fall 0.090437  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[3]}]
set_driving_cell -fall -min -library USERLIB_nldm_tt_1p00v_1p00v_25c -lib_cell sram_sp_hdc_svt_rvt_hvt -from_pin CLK -pin {Q[3]} -input_transition_rise 0.105968  -input_transition_fall 0.090437  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[3]}]
set_input_delay  0.899995 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[3]}]
set_input_delay  0.897254 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[3]}]
set_input_delay  0.902502 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[3]}]
set_input_delay  0.89976 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[3]}]
set_driving_cell -rise -max -library USERLIB_nldm_tt_1p00v_1p00v_25c -lib_cell sram_sp_hdc_svt_rvt_hvt -from_pin CLK -pin {Q[2]} -input_transition_rise 0.190491  -input_transition_fall 0.174569  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[2]}]
set_driving_cell -fall -max -library USERLIB_nldm_tt_1p00v_1p00v_25c -lib_cell sram_sp_hdc_svt_rvt_hvt -from_pin CLK -pin {Q[2]} -input_transition_rise 0.190491  -input_transition_fall 0.174569  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[2]}]
set_driving_cell -rise -min -library USERLIB_nldm_tt_1p00v_1p00v_25c -lib_cell sram_sp_hdc_svt_rvt_hvt -from_pin CLK -pin {Q[2]} -input_transition_rise 0.105968  -input_transition_fall 0.090437  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[2]}]
set_driving_cell -fall -min -library USERLIB_nldm_tt_1p00v_1p00v_25c -lib_cell sram_sp_hdc_svt_rvt_hvt -from_pin CLK -pin {Q[2]} -input_transition_rise 0.105968  -input_transition_fall 0.090437  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[2]}]
set_input_delay  0.891784 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[2]}]
set_input_delay  0.889042 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[2]}]
set_input_delay  0.89145 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[2]}]
set_input_delay  0.888708 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[2]}]
set_driving_cell -rise -max -library USERLIB_nldm_tt_1p00v_1p00v_25c -lib_cell sram_sp_hdc_svt_rvt_hvt -from_pin CLK -pin {Q[1]} -input_transition_rise 0.190491  -input_transition_fall 0.174569  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[1]}]
set_driving_cell -fall -max -library USERLIB_nldm_tt_1p00v_1p00v_25c -lib_cell sram_sp_hdc_svt_rvt_hvt -from_pin CLK -pin {Q[1]} -input_transition_rise 0.190491  -input_transition_fall 0.174569  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[1]}]
set_driving_cell -rise -min -library USERLIB_nldm_tt_1p00v_1p00v_25c -lib_cell sram_sp_hdc_svt_rvt_hvt -from_pin CLK -pin {Q[1]} -input_transition_rise 0.105968  -input_transition_fall 0.090437  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[1]}]
set_driving_cell -fall -min -library USERLIB_nldm_tt_1p00v_1p00v_25c -lib_cell sram_sp_hdc_svt_rvt_hvt -from_pin CLK -pin {Q[1]} -input_transition_rise 0.105968  -input_transition_fall 0.090437  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[1]}]
set_input_delay  0.89843 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[1]}]
set_input_delay  0.89569 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[1]}]
set_input_delay  0.899873 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[1]}]
set_input_delay  0.897132 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[1]}]
set_driving_cell -rise -max -library USERLIB_nldm_tt_1p00v_1p00v_25c -lib_cell sram_sp_hdc_svt_rvt_hvt -from_pin CLK -pin {Q[0]} -input_transition_rise 0.190491  -input_transition_fall 0.174569  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[0]}]
set_driving_cell -fall -max -library USERLIB_nldm_tt_1p00v_1p00v_25c -lib_cell sram_sp_hdc_svt_rvt_hvt -from_pin CLK -pin {Q[0]} -input_transition_rise 0.190491  -input_transition_fall 0.174569  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[0]}]
set_driving_cell -rise -min -library USERLIB_nldm_tt_1p00v_1p00v_25c -lib_cell sram_sp_hdc_svt_rvt_hvt -from_pin CLK -pin {Q[0]} -input_transition_rise 0.105968  -input_transition_fall 0.090437  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[0]}]
set_driving_cell -fall -min -library USERLIB_nldm_tt_1p00v_1p00v_25c -lib_cell sram_sp_hdc_svt_rvt_hvt -from_pin CLK -pin {Q[0]} -input_transition_rise 0.105968  -input_transition_fall 0.090437  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[0]}]
set_input_delay  0.895144 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[0]}]
set_input_delay  0.892403 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[0]}]
set_input_delay  0.895331 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[0]}]
set_input_delay  0.892589 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[0]}]
set_output_delay  0.0785918 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_chip_select}]
set_output_delay  -0.245242 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_chip_select}]
set_output_delay  0.0169933 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_chip_select}]
set_output_delay  -0.157149 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_chip_select}]
set_load -pin_load -max  0.001737 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_chip_select}]
set_load -pin_load -max  0.001737 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_chip_select}]
set_load -pin_load -min  0.001737 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_chip_select}]
set_load -pin_load -min  0.001737 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_chip_select}]
# set_case_analysis 1 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3__Logic1_}]
# set_case_analysis 0 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3__Logic0_}]
set_driving_cell -rise -max -library USERLIB_nldm_tt_1p00v_1p00v_25c -lib_cell sram_sp_hdc_svt_rvt_hvt -from_pin CLK -pin {Q[7]} -input_transition_rise 0.191016  -input_transition_fall 0.175136  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[7]}]
set_driving_cell -fall -max -library USERLIB_nldm_tt_1p00v_1p00v_25c -lib_cell sram_sp_hdc_svt_rvt_hvt -from_pin CLK -pin {Q[7]} -input_transition_rise 0.191016  -input_transition_fall 0.175136  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[7]}]
set_driving_cell -rise -min -library USERLIB_nldm_tt_1p00v_1p00v_25c -lib_cell sram_sp_hdc_svt_rvt_hvt -from_pin CLK -pin {Q[7]} -input_transition_rise 0.105968  -input_transition_fall 0.090437  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[7]}]
set_driving_cell -fall -min -library USERLIB_nldm_tt_1p00v_1p00v_25c -lib_cell sram_sp_hdc_svt_rvt_hvt -from_pin CLK -pin {Q[7]} -input_transition_rise 0.105968  -input_transition_fall 0.090437  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[7]}]
set_input_delay  0.89547 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[7]}]
set_input_delay  0.892712 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[7]}]
set_input_delay  0.896257 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[7]}]
set_input_delay  0.893498 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[7]}]
set_driving_cell -rise -max -library USERLIB_nldm_tt_1p00v_1p00v_25c -lib_cell sram_sp_hdc_svt_rvt_hvt -from_pin CLK -pin {Q[6]} -input_transition_rise 0.191016  -input_transition_fall 0.175136  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[6]}]
set_driving_cell -fall -max -library USERLIB_nldm_tt_1p00v_1p00v_25c -lib_cell sram_sp_hdc_svt_rvt_hvt -from_pin CLK -pin {Q[6]} -input_transition_rise 0.191016  -input_transition_fall 0.175136  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[6]}]
set_driving_cell -rise -min -library USERLIB_nldm_tt_1p00v_1p00v_25c -lib_cell sram_sp_hdc_svt_rvt_hvt -from_pin CLK -pin {Q[6]} -input_transition_rise 0.105968  -input_transition_fall 0.090437  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[6]}]
set_driving_cell -fall -min -library USERLIB_nldm_tt_1p00v_1p00v_25c -lib_cell sram_sp_hdc_svt_rvt_hvt -from_pin CLK -pin {Q[6]} -input_transition_rise 0.105968  -input_transition_fall 0.090437  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[6]}]
set_input_delay  0.882768 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[6]}]
set_input_delay  0.880009 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[6]}]
set_input_delay  0.878347 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[6]}]
set_input_delay  0.875588 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[6]}]
set_driving_cell -rise -max -library USERLIB_nldm_tt_1p00v_1p00v_25c -lib_cell sram_sp_hdc_svt_rvt_hvt -from_pin CLK -pin {Q[5]} -input_transition_rise 0.191016  -input_transition_fall 0.175136  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[5]}]
set_driving_cell -fall -max -library USERLIB_nldm_tt_1p00v_1p00v_25c -lib_cell sram_sp_hdc_svt_rvt_hvt -from_pin CLK -pin {Q[5]} -input_transition_rise 0.191016  -input_transition_fall 0.175136  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[5]}]
set_driving_cell -rise -min -library USERLIB_nldm_tt_1p00v_1p00v_25c -lib_cell sram_sp_hdc_svt_rvt_hvt -from_pin CLK -pin {Q[5]} -input_transition_rise 0.105968  -input_transition_fall 0.090437  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[5]}]
set_driving_cell -fall -min -library USERLIB_nldm_tt_1p00v_1p00v_25c -lib_cell sram_sp_hdc_svt_rvt_hvt -from_pin CLK -pin {Q[5]} -input_transition_rise 0.105968  -input_transition_fall 0.090437  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[5]}]
set_input_delay  0.886549 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[5]}]
set_input_delay  0.883789 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[5]}]
set_input_delay  0.884261 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[5]}]
set_input_delay  0.881502 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[5]}]
set_driving_cell -rise -max -library USERLIB_nldm_tt_1p00v_1p00v_25c -lib_cell sram_sp_hdc_svt_rvt_hvt -from_pin CLK -pin {Q[4]} -input_transition_rise 0.191016  -input_transition_fall 0.175136  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[4]}]
set_driving_cell -fall -max -library USERLIB_nldm_tt_1p00v_1p00v_25c -lib_cell sram_sp_hdc_svt_rvt_hvt -from_pin CLK -pin {Q[4]} -input_transition_rise 0.191016  -input_transition_fall 0.175136  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[4]}]
set_driving_cell -rise -min -library USERLIB_nldm_tt_1p00v_1p00v_25c -lib_cell sram_sp_hdc_svt_rvt_hvt -from_pin CLK -pin {Q[4]} -input_transition_rise 0.105968  -input_transition_fall 0.090437  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[4]}]
set_driving_cell -fall -min -library USERLIB_nldm_tt_1p00v_1p00v_25c -lib_cell sram_sp_hdc_svt_rvt_hvt -from_pin CLK -pin {Q[4]} -input_transition_rise 0.105968  -input_transition_fall 0.090437  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[4]}]
set_input_delay  0.887661 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[4]}]
set_input_delay  0.884902 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[4]}]
set_input_delay  0.885248 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[4]}]
set_input_delay  0.882489 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[4]}]
set_driving_cell -rise -max -library USERLIB_nldm_tt_1p00v_1p00v_25c -lib_cell sram_sp_hdc_svt_rvt_hvt -from_pin CLK -pin {Q[3]} -input_transition_rise 0.191016  -input_transition_fall 0.175136  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[3]}]
set_driving_cell -fall -max -library USERLIB_nldm_tt_1p00v_1p00v_25c -lib_cell sram_sp_hdc_svt_rvt_hvt -from_pin CLK -pin {Q[3]} -input_transition_rise 0.191016  -input_transition_fall 0.175136  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[3]}]
set_driving_cell -rise -min -library USERLIB_nldm_tt_1p00v_1p00v_25c -lib_cell sram_sp_hdc_svt_rvt_hvt -from_pin CLK -pin {Q[3]} -input_transition_rise 0.105968  -input_transition_fall 0.090437  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[3]}]
set_driving_cell -fall -min -library USERLIB_nldm_tt_1p00v_1p00v_25c -lib_cell sram_sp_hdc_svt_rvt_hvt -from_pin CLK -pin {Q[3]} -input_transition_rise 0.105968  -input_transition_fall 0.090437  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[3]}]
set_input_delay  0.885496 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[3]}]
set_input_delay  0.882737 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[3]}]
set_input_delay  0.882442 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[3]}]
set_input_delay  0.879683 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[3]}]
set_driving_cell -rise -max -library USERLIB_nldm_tt_1p00v_1p00v_25c -lib_cell sram_sp_hdc_svt_rvt_hvt -from_pin CLK -pin {Q[2]} -input_transition_rise 0.191016  -input_transition_fall 0.175136  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[2]}]
set_driving_cell -fall -max -library USERLIB_nldm_tt_1p00v_1p00v_25c -lib_cell sram_sp_hdc_svt_rvt_hvt -from_pin CLK -pin {Q[2]} -input_transition_rise 0.191016  -input_transition_fall 0.175136  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[2]}]
set_driving_cell -rise -min -library USERLIB_nldm_tt_1p00v_1p00v_25c -lib_cell sram_sp_hdc_svt_rvt_hvt -from_pin CLK -pin {Q[2]} -input_transition_rise 0.105968  -input_transition_fall 0.090437  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[2]}]
set_driving_cell -fall -min -library USERLIB_nldm_tt_1p00v_1p00v_25c -lib_cell sram_sp_hdc_svt_rvt_hvt -from_pin CLK -pin {Q[2]} -input_transition_rise 0.105968  -input_transition_fall 0.090437  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[2]}]
set_input_delay  0.882573 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[2]}]
set_input_delay  0.879814 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[2]}]
set_input_delay  0.878351 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[2]}]
set_input_delay  0.875592 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[2]}]
set_driving_cell -rise -max -library USERLIB_nldm_tt_1p00v_1p00v_25c -lib_cell sram_sp_hdc_svt_rvt_hvt -from_pin CLK -pin {Q[1]} -input_transition_rise 0.191016  -input_transition_fall 0.175136  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[1]}]
set_driving_cell -fall -max -library USERLIB_nldm_tt_1p00v_1p00v_25c -lib_cell sram_sp_hdc_svt_rvt_hvt -from_pin CLK -pin {Q[1]} -input_transition_rise 0.191016  -input_transition_fall 0.175136  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[1]}]
set_driving_cell -rise -min -library USERLIB_nldm_tt_1p00v_1p00v_25c -lib_cell sram_sp_hdc_svt_rvt_hvt -from_pin CLK -pin {Q[1]} -input_transition_rise 0.105968  -input_transition_fall 0.090437  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[1]}]
set_driving_cell -fall -min -library USERLIB_nldm_tt_1p00v_1p00v_25c -lib_cell sram_sp_hdc_svt_rvt_hvt -from_pin CLK -pin {Q[1]} -input_transition_rise 0.105968  -input_transition_fall 0.090437  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[1]}]
set_input_delay  0.892498 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[1]}]
set_input_delay  0.88974 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[1]}]
set_input_delay  0.891581 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[1]}]
set_input_delay  0.888822 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[1]}]
set_driving_cell -rise -max -library USERLIB_nldm_tt_1p00v_1p00v_25c -lib_cell sram_sp_hdc_svt_rvt_hvt -from_pin CLK -pin {Q[0]} -input_transition_rise 0.191016  -input_transition_fall 0.175136  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[0]}]
set_driving_cell -fall -max -library USERLIB_nldm_tt_1p00v_1p00v_25c -lib_cell sram_sp_hdc_svt_rvt_hvt -from_pin CLK -pin {Q[0]} -input_transition_rise 0.191016  -input_transition_fall 0.175136  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[0]}]
set_driving_cell -rise -min -library USERLIB_nldm_tt_1p00v_1p00v_25c -lib_cell sram_sp_hdc_svt_rvt_hvt -from_pin CLK -pin {Q[0]} -input_transition_rise 0.105968  -input_transition_fall 0.090437  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[0]}]
set_driving_cell -fall -min -library USERLIB_nldm_tt_1p00v_1p00v_25c -lib_cell sram_sp_hdc_svt_rvt_hvt -from_pin CLK -pin {Q[0]} -input_transition_rise 0.105968  -input_transition_fall 0.090437  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[0]}]
set_input_delay  0.892514 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[0]}]
set_input_delay  0.889756 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[0]}]
set_input_delay  0.892152 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[0]}]
set_input_delay  0.889392 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_data_out[0]}]
set_output_delay  0.0649625 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_chip_select}]
set_output_delay  -0.249972 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_chip_select}]
set_output_delay  0.0108241 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_chip_select}]
set_output_delay  -0.170825 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_chip_select}]
set_load -pin_load -max  0.001737 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_chip_select}]
set_load -pin_load -max  0.001737 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_chip_select}]
set_load -pin_load -min  0.001737 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_chip_select}]
set_load -pin_load -min  0.001737 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2_chip_select}]
# set_case_analysis 1 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2__Logic1_}]
# set_case_analysis 0 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM2__Logic0_}]
set_output_delay  0.235192 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_n3}]
set_output_delay  -0.0544997 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_n3}]
set_output_delay  0.198086 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_n3}]
set_output_delay  -0.0510875 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_n3}]
set_load -pin_load -max  0.001424 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_n3}]
set_load -pin_load -max  0.001424 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_n3}]
set_load -pin_load -min  0.001424 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_n3}]
set_load -pin_load -min  0.001424 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_n3}]
set_output_delay  0.253372 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_n2}]
set_output_delay  -0.0353725 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_n2}]
set_output_delay  0.226757 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_n2}]
set_output_delay  -0.0207409 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_n2}]
set_load -pin_load -max  0.001424 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_n2}]
set_load -pin_load -max  0.001424 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_n2}]
set_load -pin_load -min  0.001424 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_n2}]
set_load -pin_load -min  0.001424 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_n2}]
set_output_delay  0.216557 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[31]}]
set_output_delay  0.00881211 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[31]}]
set_output_delay  0.211208 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[31]}]
set_output_delay  -0.0219505 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[31]}]
set_load -pin_load -max  0.001424 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[31]}]
set_load -pin_load -max  0.001424 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[31]}]
set_load -pin_load -min  0.001424 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[31]}]
set_load -pin_load -min  0.001424 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[31]}]
set_output_delay  0.238844 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[30]}]
set_output_delay  0.0317943 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[30]}]
set_output_delay  0.210017 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[30]}]
set_output_delay  -0.0225492 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[30]}]
set_load -pin_load -max  0.001506 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[30]}]
set_load -pin_load -max  0.001506 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[30]}]
set_load -pin_load -min  0.001506 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[30]}]
set_load -pin_load -min  0.001506 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[30]}]
set_output_delay  0.233529 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[29]}]
set_output_delay  0.0263215 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[29]}]
set_output_delay  0.19816 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[29]}]
set_output_delay  -0.0343966 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[29]}]
set_load -pin_load -max  0.001506 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[29]}]
set_load -pin_load -max  0.001506 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[29]}]
set_load -pin_load -min  0.001506 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[29]}]
set_load -pin_load -min  0.001506 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[29]}]
set_output_delay  0.263148 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[28]}]
set_output_delay  0.0561502 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[28]}]
set_output_delay  0.245951 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[28]}]
set_output_delay  0.0134041 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[28]}]
set_load -pin_load -max  0.001424 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[28]}]
set_load -pin_load -max  0.001424 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[28]}]
set_load -pin_load -min  0.001424 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[28]}]
set_load -pin_load -min  0.001424 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[28]}]
set_output_delay  0.241823 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[27]}]
set_output_delay  0.0344187 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[27]}]
set_output_delay  0.247089 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[27]}]
set_output_delay  0.014728 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[27]}]
set_load -pin_load -max  0.001424 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[27]}]
set_load -pin_load -max  0.001424 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[27]}]
set_load -pin_load -min  0.001424 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[27]}]
set_load -pin_load -min  0.001424 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[27]}]
set_output_delay  0.246253 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[26]}]
set_output_delay  0.0389963 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[26]}]
set_output_delay  0.239944 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[26]}]
set_output_delay  0.00740105 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[26]}]
set_load -pin_load -max  0.000951 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[26]}]
set_load -pin_load -max  0.000951 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[26]}]
set_load -pin_load -min  0.000951 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[26]}]
set_load -pin_load -min  0.000951 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[26]}]
set_output_delay  0.274313 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[25]}]
set_output_delay  0.0675358 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[25]}]
set_output_delay  0.271429 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[25]}]
set_output_delay  0.0392733 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[25]}]
set_load -pin_load -max  0.001424 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[25]}]
set_load -pin_load -max  0.001424 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[25]}]
set_load -pin_load -min  0.001424 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[25]}]
set_load -pin_load -min  0.001424 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[25]}]
set_output_delay  -0.000308457 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[24]}]
set_output_delay  -0.207451 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[24]}]
set_output_delay  -0.00811751 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[24]}]
set_output_delay  -0.239997 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[24]}]
set_load -pin_load -max  0.001537 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[24]}]
set_load -pin_load -max  0.001537 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[24]}]
set_load -pin_load -min  0.001537 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[24]}]
set_load -pin_load -min  0.001537 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[24]}]
set_output_delay  0.297143 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[23]}]
set_output_delay  0.0894449 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[23]}]
set_output_delay  0.271104 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[23]}]
set_output_delay  0.0381879 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[23]}]
set_load -pin_load -max  0.001424 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[23]}]
set_load -pin_load -max  0.001424 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[23]}]
set_load -pin_load -min  0.001424 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[23]}]
set_load -pin_load -min  0.001424 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[23]}]
set_output_delay  0.265434 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[22]}]
set_output_delay  0.0579878 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[22]}]
set_output_delay  0.252141 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[22]}]
set_output_delay  0.0195037 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[22]}]
set_load -pin_load -max  0.001424 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[22]}]
set_load -pin_load -max  0.001424 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[22]}]
set_load -pin_load -min  0.001424 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[22]}]
set_load -pin_load -min  0.001424 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[22]}]
set_output_delay  0.290901 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[21]}]
set_output_delay  0.0836098 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[21]}]
set_output_delay  0.251101 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[21]}]
set_output_delay  0.0185267 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[21]}]
set_load -pin_load -max  0.001506 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[21]}]
set_load -pin_load -max  0.001506 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[21]}]
set_load -pin_load -min  0.001506 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[21]}]
set_load -pin_load -min  0.001506 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[21]}]
set_output_delay  0.25879 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[20]}]
set_output_delay  0.0512953 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[20]}]
set_output_delay  0.24891 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[20]}]
set_output_delay  0.0162686 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[20]}]
set_load -pin_load -max  0.001424 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[20]}]
set_load -pin_load -max  0.001424 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[20]}]
set_load -pin_load -min  0.001424 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[20]}]
set_load -pin_load -min  0.001424 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[20]}]
set_output_delay  0.234133 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[19]}]
set_output_delay  0.0266537 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[19]}]
set_output_delay  0.232571 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[19]}]
set_output_delay  2.58521e-05 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[19]}]
set_load -pin_load -max  0.001424 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[19]}]
set_load -pin_load -max  0.001424 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[19]}]
set_load -pin_load -min  0.001424 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[19]}]
set_load -pin_load -min  0.001424 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[19]}]
set_output_delay  0.0205925 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[18]}]
set_output_delay  -0.18586 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[18]}]
set_output_delay  0.0102907 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[18]}]
set_output_delay  -0.220418 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[18]}]
set_load -pin_load -max  0.001537 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[18]}]
set_load -pin_load -max  0.001537 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[18]}]
set_load -pin_load -min  0.001537 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[18]}]
set_load -pin_load -min  0.001537 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[18]}]
set_output_delay  0.23037 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[17]}]
set_output_delay  0.0226887 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[17]}]
set_output_delay  0.239403 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[17]}]
set_output_delay  0.0069294 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[17]}]
set_load -pin_load -max  0.001424 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[17]}]
set_load -pin_load -max  0.001424 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[17]}]
set_load -pin_load -min  0.001424 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[17]}]
set_load -pin_load -min  0.001424 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[17]}]
set_output_delay  0.225189 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[16]}]
set_output_delay  0.0174976 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[16]}]
set_output_delay  0.235827 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[16]}]
set_output_delay  0.00337217 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[16]}]
set_load -pin_load -max  0.001424 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[16]}]
set_load -pin_load -max  0.001424 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[16]}]
set_load -pin_load -min  0.001424 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[16]}]
set_load -pin_load -min  0.001424 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[16]}]
set_output_delay  0.393113 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[11]}]
set_output_delay  -0.035915 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[11]}]
set_output_delay  0.379629 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[11]}]
set_output_delay  -0.011982 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[11]}]
set_load -pin_load -max  0.00293 [get_ports {u_ahb_ram_genblk3_SRAMADDR[11]}]
set_load -pin_load -max  0.00293 [get_ports {u_ahb_ram_genblk3_SRAMADDR[11]}]
set_load -pin_load -min  0.00293 [get_ports {u_ahb_ram_genblk3_SRAMADDR[11]}]
set_load -pin_load -min  0.00293 [get_ports {u_ahb_ram_genblk3_SRAMADDR[11]}]
set_output_delay  0.234419 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[10]}]
set_output_delay  -0.241825 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[10]}]
set_output_delay  0.216603 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[10]}]
set_output_delay  -0.203697 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[10]}]
set_load -pin_load -max  0.007052 [get_ports {u_ahb_ram_genblk3_SRAMADDR[10]}]
set_load -pin_load -max  0.007052 [get_ports {u_ahb_ram_genblk3_SRAMADDR[10]}]
set_load -pin_load -min  0.007052 [get_ports {u_ahb_ram_genblk3_SRAMADDR[10]}]
set_load -pin_load -min  0.007052 [get_ports {u_ahb_ram_genblk3_SRAMADDR[10]}]
set_output_delay  0.323702 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[9]}]
set_output_delay  -0.241253 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[9]}]
set_output_delay  0.308487 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[9]}]
set_output_delay  -0.204418 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[9]}]
set_load -pin_load -max  0.00697 [get_ports {u_ahb_ram_genblk3_SRAMADDR[9]}]
set_load -pin_load -max  0.00697 [get_ports {u_ahb_ram_genblk3_SRAMADDR[9]}]
set_load -pin_load -min  0.00697 [get_ports {u_ahb_ram_genblk3_SRAMADDR[9]}]
set_load -pin_load -min  0.00697 [get_ports {u_ahb_ram_genblk3_SRAMADDR[9]}]
set_output_delay  0.268227 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[8]}]
set_output_delay  -0.232224 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[8]}]
set_output_delay  0.227532 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[8]}]
set_output_delay  -0.196393 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[8]}]
set_load -pin_load -max  0.007052 [get_ports {u_ahb_ram_genblk3_SRAMADDR[8]}]
set_load -pin_load -max  0.007052 [get_ports {u_ahb_ram_genblk3_SRAMADDR[8]}]
set_load -pin_load -min  0.007052 [get_ports {u_ahb_ram_genblk3_SRAMADDR[8]}]
set_load -pin_load -min  0.007052 [get_ports {u_ahb_ram_genblk3_SRAMADDR[8]}]
set_output_delay  0.397317 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[7]}]
set_output_delay  -0.245302 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[7]}]
set_output_delay  0.356451 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[7]}]
set_output_delay  -0.219535 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[7]}]
set_load -pin_load -max  0.00697 [get_ports {u_ahb_ram_genblk3_SRAMADDR[7]}]
set_load -pin_load -max  0.00697 [get_ports {u_ahb_ram_genblk3_SRAMADDR[7]}]
set_load -pin_load -min  0.00697 [get_ports {u_ahb_ram_genblk3_SRAMADDR[7]}]
set_load -pin_load -min  0.00697 [get_ports {u_ahb_ram_genblk3_SRAMADDR[7]}]
set_output_delay  0.312832 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[6]}]
set_output_delay  -0.240192 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[6]}]
set_output_delay  0.286649 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[6]}]
set_output_delay  -0.216616 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[6]}]
set_load -pin_load -max  0.006583 [get_ports {u_ahb_ram_genblk3_SRAMADDR[6]}]
set_load -pin_load -max  0.006583 [get_ports {u_ahb_ram_genblk3_SRAMADDR[6]}]
set_load -pin_load -min  0.006583 [get_ports {u_ahb_ram_genblk3_SRAMADDR[6]}]
set_load -pin_load -min  0.006583 [get_ports {u_ahb_ram_genblk3_SRAMADDR[6]}]
set_output_delay  0.260935 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[5]}]
set_output_delay  -0.273223 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[5]}]
set_output_delay  0.242711 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[5]}]
set_output_delay  -0.23846 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[5]}]
set_load -pin_load -max  0.007052 [get_ports {u_ahb_ram_genblk3_SRAMADDR[5]}]
set_load -pin_load -max  0.007052 [get_ports {u_ahb_ram_genblk3_SRAMADDR[5]}]
set_load -pin_load -min  0.007052 [get_ports {u_ahb_ram_genblk3_SRAMADDR[5]}]
set_load -pin_load -min  0.007052 [get_ports {u_ahb_ram_genblk3_SRAMADDR[5]}]
set_output_delay  0.361256 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[4]}]
set_output_delay  -0.0259883 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[4]}]
set_output_delay  0.359052 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[4]}]
set_output_delay  0.0274767 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[4]}]
set_load -pin_load -max  0.002848 [get_ports {u_ahb_ram_genblk3_SRAMADDR[4]}]
set_load -pin_load -max  0.002848 [get_ports {u_ahb_ram_genblk3_SRAMADDR[4]}]
set_load -pin_load -min  0.002848 [get_ports {u_ahb_ram_genblk3_SRAMADDR[4]}]
set_load -pin_load -min  0.002848 [get_ports {u_ahb_ram_genblk3_SRAMADDR[4]}]
set_output_delay  0.31551 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[3]}]
set_output_delay  -0.248246 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[3]}]
set_output_delay  0.283852 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[3]}]
set_output_delay  -0.209697 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[3]}]
set_load -pin_load -max  0.007052 [get_ports {u_ahb_ram_genblk3_SRAMADDR[3]}]
set_load -pin_load -max  0.007052 [get_ports {u_ahb_ram_genblk3_SRAMADDR[3]}]
set_load -pin_load -min  0.007052 [get_ports {u_ahb_ram_genblk3_SRAMADDR[3]}]
set_load -pin_load -min  0.007052 [get_ports {u_ahb_ram_genblk3_SRAMADDR[3]}]
set_output_delay  0.337104 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[2]}]
set_output_delay  -0.23564 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[2]}]
set_output_delay  0.28386 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[2]}]
set_output_delay  -0.213344 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[2]}]
set_load -pin_load -max  0.007052 [get_ports {u_ahb_ram_genblk3_SRAMADDR[2]}]
set_load -pin_load -max  0.007052 [get_ports {u_ahb_ram_genblk3_SRAMADDR[2]}]
set_load -pin_load -min  0.007052 [get_ports {u_ahb_ram_genblk3_SRAMADDR[2]}]
set_load -pin_load -min  0.007052 [get_ports {u_ahb_ram_genblk3_SRAMADDR[2]}]
set_output_delay  0.301967 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[1]}]
set_output_delay  -0.252901 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[1]}]
set_output_delay  0.270594 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[1]}]
set_output_delay  -0.224983 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[1]}]
set_load -pin_load -max  0.007052 [get_ports {u_ahb_ram_genblk3_SRAMADDR[1]}]
set_load -pin_load -max  0.007052 [get_ports {u_ahb_ram_genblk3_SRAMADDR[1]}]
set_load -pin_load -min  0.007052 [get_ports {u_ahb_ram_genblk3_SRAMADDR[1]}]
set_load -pin_load -min  0.007052 [get_ports {u_ahb_ram_genblk3_SRAMADDR[1]}]
set_output_delay  0.298823 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[0]}]
set_output_delay  -0.0834778 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[0]}]
set_output_delay  0.254099 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[0]}]
set_output_delay  -0.0610105 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[0]}]
set_load -pin_load -max  0.002543 [get_ports {u_ahb_ram_genblk3_SRAMADDR[0]}]
set_load -pin_load -max  0.002543 [get_ports {u_ahb_ram_genblk3_SRAMADDR[0]}]
set_load -pin_load -min  0.002543 [get_ports {u_ahb_ram_genblk3_SRAMADDR[0]}]
set_load -pin_load -min  0.002543 [get_ports {u_ahb_ram_genblk3_SRAMADDR[0]}]
set_load -pin_load -max  0.061808 [get_ports {gated_hclk}]
set_load -pin_load -max  0.061808 [get_ports {gated_hclk}]
set_load -pin_load -min  0.061808 [get_ports {gated_hclk}]
set_load -pin_load -min  0.061808 [get_ports {gated_hclk}]
set_clock_latency -source -rise -late  -clock [get_clocks {XTAL1}]  0.000631259 [get_ports {XTAL1}]
set_clock_latency -source -rise -early  -clock [get_clocks {XTAL1}]  8.78924e-05 [get_ports {XTAL1}]
set_clock_latency -source -fall -late  -clock [get_clocks {XTAL1}]  0.000631259 [get_ports {XTAL1}]
set_clock_latency -source -fall -early  -clock [get_clocks {XTAL1}]  8.78924e-05 [get_ports {XTAL1}]
set_propagated_clock [get_pins {CTS_ccl_a_BUF_XTAL1_G0_L1_1/A}]
set_propagated_clock [get_pins {u_cortexm0_pmu/u_hclk/ICGCell/CK}]
set_propagated_clock [get_pins {u_cmsdk_mcu_clkctrl/U3/B}]
set_input_delay  0.288469 -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {SWDIOTMS}]
set_input_delay  0.319651 -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {SWDIOTMS}]
set_input_delay  0.000687589 -min -add_delay -network_latency_included -source_latency_included [get_ports {SWDIOTMS}]
set_input_delay  0.0048346 -max -add_delay -network_latency_included -source_latency_included [get_ports {SWCLKTCK}]
set_input_delay  0.000161963 -min -add_delay -network_latency_included -source_latency_included [get_ports {SWCLKTCK}]
set_input_delay  0.000309705 -add_delay -network_latency_included -source_latency_included [get_ports {P1[15]}]
set_input_delay  0.408302 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {P1[15]}]
set_input_delay  0.319298 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {P1[15]}]
set_input_delay  0.439789 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {P1[15]}]
set_input_delay  0.310777 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {P1[15]}]
set_input_delay  0.00054316 -add_delay -network_latency_included -source_latency_included [get_ports {P1[14]}]
set_input_delay  0.401012 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {P1[14]}]
set_input_delay  0.31656 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {P1[14]}]
set_input_delay  0.432342 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {P1[14]}]
set_input_delay  0.308089 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {P1[14]}]
set_input_delay  0.000192471 -add_delay -network_latency_included -source_latency_included [get_ports {P1[13]}]
set_input_delay  0.413426 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {P1[13]}]
set_input_delay  0.317672 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {P1[13]}]
set_input_delay  0.450348 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {P1[13]}]
set_input_delay  0.309182 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {P1[13]}]
set_input_delay  0.0015386 -add_delay -network_latency_included -source_latency_included [get_ports {P1[12]}]
set_input_delay  0.424229 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {P1[12]}]
set_input_delay  0.320641 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {P1[12]}]
set_input_delay  0.468131 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {P1[12]}]
set_input_delay  0.312056 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {P1[12]}]
set_input_delay  0.000778702 -add_delay -network_latency_included -source_latency_included [get_ports {P1[11]}]
set_input_delay  0.435984 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {P1[11]}]
set_input_delay  0.325096 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {P1[11]}]
set_input_delay  0.479059 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {P1[11]}]
set_input_delay  0.316411 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {P1[11]}]
set_input_delay  0.00051487 -add_delay -network_latency_included -source_latency_included [get_ports {P1[10]}]
set_input_delay  0.419315 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {P1[10]}]
set_input_delay  0.319229 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {P1[10]}]
set_input_delay  0.46229 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {P1[10]}]
set_input_delay  0.310707 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {P1[10]}]
set_input_delay  0.00233321 -max -add_delay -network_latency_included -source_latency_included [get_ports {P1[9]}]
set_input_delay  0.0014953 -min -add_delay -network_latency_included -source_latency_included [get_ports {P1[9]}]
set_input_delay  0.40341 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {P1[9]}]
set_input_delay  0.316685 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {P1[9]}]
set_input_delay  0.434539 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {P1[9]}]
set_input_delay  0.30819 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {P1[9]}]
set_input_delay  0.00144641 -max -add_delay -network_latency_included -source_latency_included [get_ports {P1[8]}]
set_input_delay  0.0014266 -min -add_delay -network_latency_included -source_latency_included [get_ports {P1[8]}]
set_input_delay  0.417782 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {P1[8]}]
set_input_delay  0.323694 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {P1[8]}]
set_input_delay  0.451883 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {P1[8]}]
set_input_delay  0.315031 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {P1[8]}]
set_input_delay  0.00216056 -add_delay -network_latency_included -source_latency_included [get_ports {P1[7]}]
set_input_delay  0.421393 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {P1[7]}]
set_input_delay  0.318913 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {P1[7]}]
set_input_delay  0.466993 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {P1[7]}]
set_input_delay  0.310403 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {P1[7]}]
set_input_delay  0.000219823 -add_delay -network_latency_included -source_latency_included [get_ports {P1[6]}]
set_input_delay  0.378514 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {P1[6]}]
set_input_delay  0.317855 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {P1[6]}]
set_input_delay  0.394336 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {P1[6]}]
set_input_delay  0.309363 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {P1[6]}]
set_input_delay  0.000142248 -add_delay -network_latency_included -source_latency_included [get_ports {P1[5]}]
set_input_delay  0.46236 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {P1[5]}]
set_input_delay  0.33924 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {P1[5]}]
set_input_delay  0.470418 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {P1[5]}]
set_input_delay  0.330926 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {P1[5]}]
set_input_delay  0.000410808 -max -add_delay -network_latency_included -source_latency_included [get_ports {P1[4]}]
set_input_delay  8.93693e-05 -min -add_delay -network_latency_included -source_latency_included [get_ports {P1[4]}]
set_input_delay  0.368637 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {P1[4]}]
set_input_delay  0.315342 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {P1[4]}]
set_input_delay  0.380788 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {P1[4]}]
set_input_delay  0.306849 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {P1[4]}]
set_input_delay  0.000288648 -add_delay -network_latency_included -source_latency_included [get_ports {P1[3]}]
set_input_delay  0.474655 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {P1[3]}]
set_input_delay  0.346676 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {P1[3]}]
set_input_delay  0.486867 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {P1[3]}]
set_input_delay  0.338337 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {P1[3]}]
set_input_delay  0.00066014 -max -add_delay -network_latency_included -source_latency_included [get_ports {P1[2]}]
set_input_delay  0.000463659 -min -add_delay -network_latency_included -source_latency_included [get_ports {P1[2]}]
set_input_delay  0.401069 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {P1[2]}]
set_input_delay  0.315863 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {P1[2]}]
set_input_delay  0.43516 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {P1[2]}]
set_input_delay  0.307356 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {P1[2]}]
set_input_delay  0.000768213 -add_delay -network_latency_included -source_latency_included [get_ports {P1[1]}]
set_input_delay  0.502975 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {P1[1]}]
set_input_delay  0.348881 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {P1[1]}]
set_input_delay  0.52835 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {P1[1]}]
set_input_delay  0.34053 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {P1[1]}]
set_input_delay  0.00142123 -max -add_delay -network_latency_included -source_latency_included [get_ports {P1[0]}]
set_input_delay  0.00129056 -min -add_delay -network_latency_included -source_latency_included [get_ports {P1[0]}]
set_input_delay  0.422067 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {P1[0]}]
set_input_delay  0.315787 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {P1[0]}]
set_input_delay  0.473646 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {P1[0]}]
set_input_delay  0.307286 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {P1[0]}]
set_input_delay  0.0012405 -add_delay -network_latency_included -source_latency_included [get_ports {P0[15]}]
set_input_delay  0.437994 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {P0[15]}]
set_input_delay  0.32632 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {P0[15]}]
set_input_delay  0.487687 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {P0[15]}]
set_input_delay  0.31775 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {P0[15]}]
set_input_delay  0.00131869 -add_delay -network_latency_included -source_latency_included [get_ports {P0[14]}]
set_input_delay  0.450401 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {P0[14]}]
set_input_delay  0.329435 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {P0[14]}]
set_input_delay  0.505431 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {P0[14]}]
set_input_delay  0.320802 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {P0[14]}]
set_input_delay  0.000872442 -add_delay -network_latency_included -source_latency_included [get_ports {P0[13]}]
set_input_delay  0.42228 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {P0[13]}]
set_input_delay  0.323622 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {P0[13]}]
set_input_delay  0.46191 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {P0[13]}]
set_input_delay  0.315103 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {P0[13]}]
set_input_delay  0.000203886 -add_delay -network_latency_included -source_latency_included [get_ports {P0[12]}]
set_input_delay  0.415672 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {P0[12]}]
set_input_delay  0.325567 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {P0[12]}]
set_input_delay  0.446956 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {P0[12]}]
set_input_delay  0.317012 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {P0[12]}]
set_input_delay  0.00179351 -add_delay -network_latency_included -source_latency_included [get_ports {P0[11]}]
set_input_delay  0.425969 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {P0[11]}]
set_input_delay  0.322643 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {P0[11]}]
set_input_delay  0.47265 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {P0[11]}]
set_input_delay  0.314148 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {P0[11]}]
set_input_delay  0.000558284 -add_delay -network_latency_included -source_latency_included [get_ports {P0[10]}]
set_input_delay  0.379748 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {P0[10]}]
set_input_delay  0.323491 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {P0[10]}]
set_input_delay  0.389739 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {P0[10]}]
set_input_delay  0.314981 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {P0[10]}]
set_input_delay  0.000538562 -add_delay -network_latency_included -source_latency_included [get_ports {P0[9]}]
set_input_delay  0.435332 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {P0[9]}]
set_input_delay  0.327412 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {P0[9]}]
set_input_delay  0.478922 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {P0[9]}]
set_input_delay  0.318821 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {P0[9]}]
set_input_delay  0.000572179 -add_delay -network_latency_included -source_latency_included [get_ports {P0[8]}]
set_input_delay  0.446961 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {P0[8]}]
set_input_delay  0.331845 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {P0[8]}]
set_input_delay  0.496197 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {P0[8]}]
set_input_delay  0.323164 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {P0[8]}]
set_input_delay  0.000168856 -add_delay -network_latency_included -source_latency_included [get_ports {P0[7]}]
set_input_delay  0.403521 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {P0[7]}]
set_input_delay  0.314259 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {P0[7]}]
set_input_delay  0.447784 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {P0[7]}]
set_input_delay  0.305802 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {P0[7]}]
set_input_delay  0.000205284 -add_delay -network_latency_included -source_latency_included [get_ports {P0[6]}]
set_input_delay  0.400519 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {P0[6]}]
set_input_delay  0.318516 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {P0[6]}]
set_input_delay  0.42992 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {P0[6]}]
set_input_delay  0.310062 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {P0[6]}]
set_input_delay  0.000416174 -add_delay -network_latency_included -source_latency_included [get_ports {P0[5]}]
set_input_delay  0.415989 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {P0[5]}]
set_input_delay  0.318577 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {P0[5]}]
set_input_delay  0.46189 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {P0[5]}]
set_input_delay  0.310122 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {P0[5]}]
set_input_delay  0.00071588 -add_delay -network_latency_included -source_latency_included [get_ports {P0[4]}]
set_input_delay  0.419874 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {P0[4]}]
set_input_delay  0.322886 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {P0[4]}]
set_input_delay  0.466072 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {P0[4]}]
set_input_delay  0.314364 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {P0[4]}]
set_input_delay  0.00108177 -add_delay -network_latency_included -source_latency_included [get_ports {P0[3]}]
set_input_delay  0.404334 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {P0[3]}]
set_input_delay  0.318563 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {P0[3]}]
set_input_delay  0.450794 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {P0[3]}]
set_input_delay  0.310099 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {P0[3]}]
set_input_delay  0.00159146 -add_delay -network_latency_included -source_latency_included [get_ports {P0[2]}]
set_input_delay  0.417761 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {P0[2]}]
set_input_delay  0.318984 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {P0[2]}]
set_input_delay  0.473142 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {P0[2]}]
set_input_delay  0.310521 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {P0[2]}]
set_input_delay  0.000981534 -add_delay -network_latency_included -source_latency_included [get_ports {P0[1]}]
set_input_delay  0.41864 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {P0[1]}]
set_input_delay  0.32074 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {P0[1]}]
set_input_delay  0.466342 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {P0[1]}]
set_input_delay  0.312256 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {P0[1]}]
set_input_delay  0.00100501 -add_delay -network_latency_included -source_latency_included [get_ports {P0[0]}]
set_input_delay  0.387295 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {P0[0]}]
set_input_delay  0.320988 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {P0[0]}]
set_input_delay  0.403721 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {P0[0]}]
set_input_delay  0.312483 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {P0[0]}]
set_input_delay  0.000211368 -max -add_delay -network_latency_included -source_latency_included [get_ports {NRST}]
set_input_delay  0.000197332 -min -add_delay -network_latency_included -source_latency_included [get_ports {NRST}]
###############################################################################
# Extra setting
###############################################################################
set timing_input_port_default_clock false
set auto_wire_load_selection false
set_wire_load_mode top
###############################################################################
# POCV Information
###############################################################################
