###############################################################################
#
# Created by PrimeTime on Wed Aug 26 17:45:21 2020
#
###############################################################################
# 
# Written by HyperScale Constraint Extractor
# Version : M-2017.06-SP1
# Top design name : cmsdk_mcu
# Block name : MemContext2
# Extraction Mode : normal
# Instance : u_mem_context2
# 
###############################################################################
set_units -time ns -capacitance pF -current mA -voltage V -resistance kOhm -power pW
###############################################################################
#  
# Units
# capacitive_load_unit           : 1 pF
# current_unit                   : 0.001 A
# resistance_unit                : 1 kOhm
# time_unit                      : 1 ns
# voltage_unit                   : 1 V
###############################################################################
set_operating_conditions -analysis_type on_chip_variation  -library [get_libs {scadv10_cln65gp_rvt_tt_1p0v_25c.db:scadv10_cln65gp_rvt_tt_1p0v_25c}] 
create_clock -name XTAL1 -period 2.5 -waveform { 0 1.25 } -add [get_ports {gated_hclk}]
###############################################################################
#
# Created by pt_shell on Wed Aug 26 17:45:21 2020
#
###############################################################################
# 
# Written by HyperScale Constraint Extractor
# Version : M-2017.06-SP1
# Top design name : cmsdk_mcu
# Block name : MemContext2
# Extraction Mode : normal
# Instance : u_mem_context2
# 
###############################################################################
set_clock_map XTAL1 -parent_clock XTAL1
###############################################################################
# Boundary Context Information
###############################################################################
set_max_capacitance  0.152723 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_chip_select}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_chip_select}]
set_max_capacitance  0.152723 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_n2}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_n2}]
set_max_capacitance  0.152723 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[31]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[31]}]
set_max_capacitance  0.076361 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[30]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[30]}]
set_max_capacitance  0.152723 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[29]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[29]}]
set_max_capacitance  0.076361 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[28]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[28]}]
set_max_capacitance  0.152723 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[27]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[27]}]
set_max_capacitance  0.152723 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[26]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[26]}]
set_max_capacitance  0.076361 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[25]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[25]}]
set_max_capacitance  0.152723 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[24]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[24]}]
set_max_capacitance  0.305446 [get_ports {u_ahb_ram_genblk3_SRAMADDR[11]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMADDR[11]}]
set_max_capacitance  0.305446 [get_ports {u_ahb_ram_genblk3_SRAMADDR[10]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMADDR[10]}]
set_max_capacitance  0.213812 [get_ports {u_ahb_ram_genblk3_SRAMADDR[9]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMADDR[9]}]
set_max_capacitance  0.213812 [get_ports {u_ahb_ram_genblk3_SRAMADDR[8]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMADDR[8]}]
set_max_capacitance  0.106906 [get_ports {u_ahb_ram_genblk3_SRAMADDR[7]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMADDR[7]}]
set_max_capacitance  0.106906 [get_ports {u_ahb_ram_genblk3_SRAMADDR[6]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMADDR[6]}]
set_max_capacitance  0.259629 [get_ports {u_ahb_ram_genblk3_SRAMADDR[5]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMADDR[5]}]
set_max_capacitance  0.213812 [get_ports {u_ahb_ram_genblk3_SRAMADDR[4]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMADDR[4]}]
set_max_capacitance  0.305446 [get_ports {u_ahb_ram_genblk3_SRAMADDR[3]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMADDR[3]}]
set_max_capacitance  0.106906 [get_ports {u_ahb_ram_genblk3_SRAMADDR[2]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMADDR[2]}]
set_max_capacitance  0.106906 [get_ports {u_ahb_ram_genblk3_SRAMADDR[1]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMADDR[1]}]
set_max_capacitance  0.213812 [get_ports {u_ahb_ram_genblk3_SRAMADDR[0]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMADDR[0]}]
set_max_capacitance  1.67995 [get_ports {gated_hclk}]
set_max_transition  0.699428 [get_ports {gated_hclk}]
set_output_delay  0.477103 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[7]}]
set_output_delay  0.071756 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[7]}]
set_output_delay  0.476638 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[7]}]
set_output_delay  0.0769631 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[7]}]
set_load -pin_load -max  0.001733 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[7]}]
set_load -pin_load -max  0.001733 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[7]}]
set_load -pin_load -min  0.001733 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[7]}]
set_load -pin_load -min  0.001733 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[7]}]
set_output_delay  0.486108 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[6]}]
set_output_delay  0.0760984 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[6]}]
set_output_delay  0.469089 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[6]}]
set_output_delay  0.0804836 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[6]}]
set_load -pin_load -max  0.001733 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[6]}]
set_load -pin_load -max  0.001733 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[6]}]
set_load -pin_load -min  0.001733 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[6]}]
set_load -pin_load -min  0.001733 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[6]}]
set_output_delay  0.476684 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[5]}]
set_output_delay  0.0808592 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[5]}]
set_output_delay  0.468279 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[5]}]
set_output_delay  0.0850723 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[5]}]
set_load -pin_load -max  0.001733 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[5]}]
set_load -pin_load -max  0.001733 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[5]}]
set_load -pin_load -min  0.001733 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[5]}]
set_load -pin_load -min  0.001733 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[5]}]
set_output_delay  0.5512 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[4]}]
set_output_delay  0.141142 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[4]}]
set_output_delay  0.522015 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[4]}]
set_output_delay  0.128183 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[4]}]
set_load -pin_load -max  0.001915 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[4]}]
set_load -pin_load -max  0.001915 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[4]}]
set_load -pin_load -min  0.001915 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[4]}]
set_load -pin_load -min  0.001915 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[4]}]
set_output_delay  0.479922 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[3]}]
set_output_delay  0.104754 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[3]}]
set_output_delay  0.480486 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[3]}]
set_output_delay  0.11215 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[3]}]
set_load -pin_load -max  0.001087 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[3]}]
set_load -pin_load -max  0.001087 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[3]}]
set_load -pin_load -min  0.001087 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[3]}]
set_load -pin_load -min  0.001087 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[3]}]
set_output_delay  0.48739 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[2]}]
set_output_delay  0.107822 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[2]}]
set_output_delay  0.479432 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[2]}]
set_output_delay  0.106291 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[2]}]
set_load -pin_load -max  0.001087 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[2]}]
set_load -pin_load -max  0.001087 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[2]}]
set_load -pin_load -min  0.001087 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[2]}]
set_load -pin_load -min  0.001087 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[2]}]
set_output_delay  0.488089 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[1]}]
set_output_delay  0.0898268 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[1]}]
set_output_delay  0.486011 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[1]}]
set_output_delay  0.0934784 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[1]}]
set_load -pin_load -max  0.001733 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[1]}]
set_load -pin_load -max  0.001733 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[1]}]
set_load -pin_load -min  0.001733 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[1]}]
set_load -pin_load -min  0.001733 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[1]}]
set_output_delay  0.491254 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[0]}]
set_output_delay  0.100256 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[0]}]
set_output_delay  0.487446 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[0]}]
set_output_delay  0.100218 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[0]}]
set_load -pin_load -max  0.001087 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[0]}]
set_load -pin_load -max  0.001087 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[0]}]
set_load -pin_load -min  0.001087 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[0]}]
set_load -pin_load -min  0.001087 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[0]}]
set_driving_cell -rise -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell NAND2BX1MA10TR -from_pin AN -pin Y -input_transition_rise 0.0848345  -input_transition_fall 0.0602898  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_chip_select}]
set_driving_cell -fall -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell NAND2BX1MA10TR -from_pin AN -pin Y -input_transition_rise 0.0848345  -input_transition_fall 0.0602898  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_chip_select}]
set_driving_cell -rise -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell NAND2BX1MA10TR -from_pin B -pin Y -input_transition_rise 0.0211953  -input_transition_fall 0.0177532  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_chip_select}]
set_driving_cell -fall -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell NAND2BX1MA10TR -from_pin B -pin Y -input_transition_rise 0.0211953  -input_transition_fall 0.0177532  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_chip_select}]
set_input_delay  0.976666 -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_chip_select}]
set_input_delay  0.806724 -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_chip_select}]
set_input_delay  1.03307 -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_chip_select}]
set_input_delay  0.857266 -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_chip_select}]
set_input_delay  2.34374 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_chip_select}]
set_input_delay  0.661314 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_chip_select}]
set_input_delay  2.41917 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_chip_select}]
set_input_delay  0.703091 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_chip_select}]
# set_case_analysis 1 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3__Logic1_}]
# set_case_analysis 0 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3__Logic0_}]
set_driving_cell -rise -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell NAND2X1MA10TR -from_pin B -pin Y -input_transition_rise 0.122248  -input_transition_fall 0.100709  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_n2}]
set_driving_cell -fall -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell NAND2X1MA10TR -from_pin B -pin Y -input_transition_rise 0.122248  -input_transition_fall 0.100709  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_n2}]
set_driving_cell -rise -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell NAND2X1MA10TR -from_pin A -pin Y -input_transition_rise 0.0246007  -input_transition_fall 0.0189102  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_n2}]
set_driving_cell -fall -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell NAND2X1MA10TR -from_pin A -pin Y -input_transition_rise 0.0246007  -input_transition_fall 0.0189102  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_n2}]
set_input_delay  0.98722 -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_n2}]
set_input_delay  0.865285 -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_n2}]
set_input_delay  1.06611 -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_n2}]
set_input_delay  0.970671 -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_n2}]
set_input_delay  2.3543 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_n2}]
set_input_delay  0.608118 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_n2}]
set_input_delay  2.45221 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_n2}]
set_input_delay  0.68481 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_n2}]
set_driving_cell -rise -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXT2X1MA10TR -from_pin S0 -pin Y -input_transition_rise 0.375723  -input_transition_fall 0.215311  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[31]}]
set_driving_cell -fall -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXT2X1MA10TR -from_pin S0 -pin Y -input_transition_rise 0.375723  -input_transition_fall 0.215311  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[31]}]
set_driving_cell -rise -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXT2X1MA10TR -from_pin B -pin Y -input_transition_rise 0.0173837  -input_transition_fall 0.0133995  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[31]}]
set_driving_cell -fall -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXT2X1MA10TR -from_pin B -pin Y -input_transition_rise 0.0173837  -input_transition_fall 0.0133995  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[31]}]
set_input_delay  0.712133 -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[31]}]
set_input_delay  0.685506 -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[31]}]
set_input_delay  0.88308 -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[31]}]
set_input_delay  0.866703 -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[31]}]
set_input_delay  1.52831 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[31]}]
set_input_delay  0.557708 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[31]}]
set_input_delay  1.69673 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[31]}]
set_input_delay  0.643189 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[31]}]
set_driving_cell -rise -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell DLY2X0P5MA10TR -from_pin A -pin Y -input_transition_rise 0.0852761  -input_transition_fall 0.0566489  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[30]}]
set_driving_cell -fall -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell DLY2X0P5MA10TR -from_pin A -pin Y -input_transition_rise 0.0852761  -input_transition_fall 0.0566489  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[30]}]
set_driving_cell -rise -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell DLY2X0P5MA10TR -from_pin A -pin Y -input_transition_rise 0.0799261  -input_transition_fall 0.0517483  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[30]}]
set_driving_cell -fall -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell DLY2X0P5MA10TR -from_pin A -pin Y -input_transition_rise 0.0799261  -input_transition_fall 0.0517483  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[30]}]
set_input_delay  0.858543 -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[30]}]
set_input_delay  0.83081 -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[30]}]
set_input_delay  1.04462 -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[30]}]
set_input_delay  1.0277 -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[30]}]
set_input_delay  1.70909 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[30]}]
set_input_delay  0.592162 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[30]}]
set_input_delay  1.88268 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[30]}]
set_input_delay  0.705226 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[30]}]
set_driving_cell -rise -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXT2X1MA10TR -from_pin S0 -pin Y -input_transition_rise 0.375723  -input_transition_fall 0.215311  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[29]}]
set_driving_cell -fall -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXT2X1MA10TR -from_pin S0 -pin Y -input_transition_rise 0.375723  -input_transition_fall 0.215311  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[29]}]
set_driving_cell -rise -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXT2X1MA10TR -from_pin B -pin Y -input_transition_rise 0.0186259  -input_transition_fall 0.0140799  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[29]}]
set_driving_cell -fall -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXT2X1MA10TR -from_pin B -pin Y -input_transition_rise 0.0186259  -input_transition_fall 0.0140799  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[29]}]
set_input_delay  0.716844 -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[29]}]
set_input_delay  0.690867 -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[29]}]
set_input_delay  0.89798 -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[29]}]
set_input_delay  0.880647 -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[29]}]
set_input_delay  1.53325 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[29]}]
set_input_delay  0.564765 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[29]}]
set_input_delay  1.71279 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[29]}]
set_input_delay  0.659986 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[29]}]
set_driving_cell -rise -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell DLY2X0P5MA10TR -from_pin A -pin Y -input_transition_rise 0.0991974  -input_transition_fall 0.0633297  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[28]}]
set_driving_cell -fall -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell DLY2X0P5MA10TR -from_pin A -pin Y -input_transition_rise 0.0991974  -input_transition_fall 0.0633297  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[28]}]
set_driving_cell -rise -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell DLY2X0P5MA10TR -from_pin A -pin Y -input_transition_rise 0.0948363  -input_transition_fall 0.0588118  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[28]}]
set_driving_cell -fall -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell DLY2X0P5MA10TR -from_pin A -pin Y -input_transition_rise 0.0948363  -input_transition_fall 0.0588118  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[28]}]
set_input_delay  0.925826 -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[28]}]
set_input_delay  0.900248 -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[28]}]
set_input_delay  1.16308 -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[28]}]
set_input_delay  1.1463 -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[28]}]
set_input_delay  1.76627 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[28]}]
set_input_delay  0.667815 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[28]}]
set_input_delay  1.98792 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[28]}]
set_input_delay  0.829206 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[28]}]
set_driving_cell -rise -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXT2X1MA10TR -from_pin S0 -pin Y -input_transition_rise 0.376853  -input_transition_fall 0.215313  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[27]}]
set_driving_cell -fall -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXT2X1MA10TR -from_pin S0 -pin Y -input_transition_rise 0.376853  -input_transition_fall 0.215313  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[27]}]
set_driving_cell -rise -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXT2X1MA10TR -from_pin B -pin Y -input_transition_rise 0.016839  -input_transition_fall 0.0130867  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[27]}]
set_driving_cell -fall -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXT2X1MA10TR -from_pin B -pin Y -input_transition_rise 0.016839  -input_transition_fall 0.0130867  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[27]}]
set_input_delay  0.691849 -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[27]}]
set_input_delay  0.665807 -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[27]}]
set_input_delay  0.849565 -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[27]}]
set_input_delay  0.831407 -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[27]}]
set_input_delay  1.51206 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[27]}]
set_input_delay  0.527406 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[27]}]
set_input_delay  1.66026 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[27]}]
set_input_delay  0.595475 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[27]}]
set_driving_cell -rise -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXT2X1MA10TR -from_pin S0 -pin Y -input_transition_rise 0.376646  -input_transition_fall 0.215314  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[26]}]
set_driving_cell -fall -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXT2X1MA10TR -from_pin S0 -pin Y -input_transition_rise 0.376646  -input_transition_fall 0.215314  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[26]}]
set_driving_cell -rise -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXT2X1MA10TR -from_pin B -pin Y -input_transition_rise 0.0309817  -input_transition_fall 0.0282753  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[26]}]
set_driving_cell -fall -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXT2X1MA10TR -from_pin B -pin Y -input_transition_rise 0.0309817  -input_transition_fall 0.0282753  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[26]}]
set_input_delay  0.666856 -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[26]}]
set_input_delay  0.640845 -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[26]}]
set_input_delay  0.808933 -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[26]}]
set_input_delay  0.790966 -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[26]}]
set_input_delay  1.48507 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[26]}]
set_input_delay  0.551928 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[26]}]
set_input_delay  1.62523 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[26]}]
set_input_delay  0.596675 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[26]}]
set_driving_cell -rise -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell DLY2X0P5MA10TR -from_pin A -pin Y -input_transition_rise 0.0580004  -input_transition_fall 0.0431754  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[25]}]
set_driving_cell -fall -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell DLY2X0P5MA10TR -from_pin A -pin Y -input_transition_rise 0.0580004  -input_transition_fall 0.0431754  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[25]}]
set_driving_cell -rise -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell DLY2X0P5MA10TR -from_pin A -pin Y -input_transition_rise 0.0496964  -input_transition_fall 0.0371857  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[25]}]
set_driving_cell -fall -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell DLY2X0P5MA10TR -from_pin A -pin Y -input_transition_rise 0.0496964  -input_transition_fall 0.0371857  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[25]}]
set_input_delay  0.845816 -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[25]}]
set_input_delay  0.816725 -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[25]}]
set_input_delay  1.02596 -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[25]}]
set_input_delay  1.00499 -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[25]}]
set_input_delay  1.65945 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[25]}]
set_input_delay  0.578331 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[25]}]
set_input_delay  1.83891 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[25]}]
set_input_delay  0.682268 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[25]}]
set_driving_cell -rise -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXT2X1MA10TR -from_pin S0 -pin Y -input_transition_rise 0.375725  -input_transition_fall 0.215314  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[24]}]
set_driving_cell -fall -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXT2X1MA10TR -from_pin S0 -pin Y -input_transition_rise 0.375725  -input_transition_fall 0.215314  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[24]}]
set_driving_cell -rise -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXT2X1MA10TR -from_pin B -pin Y -input_transition_rise 0.0352886  -input_transition_fall 0.0308888  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[24]}]
set_driving_cell -fall -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXT2X1MA10TR -from_pin B -pin Y -input_transition_rise 0.0352886  -input_transition_fall 0.0308888  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[24]}]
set_input_delay  0.659316 -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[24]}]
set_input_delay  0.632338 -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[24]}]
set_input_delay  0.788745 -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[24]}]
set_input_delay  0.769674 -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[24]}]
set_input_delay  1.48789 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[24]}]
set_input_delay  0.467749 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[24]}]
set_input_delay  1.59627 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[24]}]
set_input_delay  0.507844 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[24]}]
set_driving_cell -rise -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXIT2X2MA10TR -from_pin S0 -pin Y -input_transition_rise 0.229508  -input_transition_fall 0.133313  [get_ports {u_ahb_ram_genblk3_SRAMADDR[11]}]
set_driving_cell -fall -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXIT2X2MA10TR -from_pin S0 -pin Y -input_transition_rise 0.229508  -input_transition_fall 0.133313  [get_ports {u_ahb_ram_genblk3_SRAMADDR[11]}]
set_driving_cell -rise -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXIT2X2MA10TR -from_pin A -pin Y -input_transition_rise 0.0335461  -input_transition_fall 0.0204112  [get_ports {u_ahb_ram_genblk3_SRAMADDR[11]}]
set_driving_cell -fall -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXIT2X2MA10TR -from_pin A -pin Y -input_transition_rise 0.0335461  -input_transition_fall 0.0204112  [get_ports {u_ahb_ram_genblk3_SRAMADDR[11]}]
set_input_delay  0.889762 -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[11]}]
set_input_delay  0.854121 -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[11]}]
set_input_delay  0.962097 -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[11]}]
set_input_delay  0.916675 -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[11]}]
set_input_delay  2.27586 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[11]}]
set_input_delay  0.488335 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[11]}]
set_input_delay  2.34819 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[11]}]
set_input_delay  0.548399 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[11]}]
set_driving_cell -rise -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXIT2X2MA10TR -from_pin S0 -pin Y -input_transition_rise 0.229354  -input_transition_fall 0.13315  [get_ports {u_ahb_ram_genblk3_SRAMADDR[10]}]
set_driving_cell -fall -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXIT2X2MA10TR -from_pin S0 -pin Y -input_transition_rise 0.229354  -input_transition_fall 0.13315  [get_ports {u_ahb_ram_genblk3_SRAMADDR[10]}]
set_driving_cell -rise -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXIT2X2MA10TR -from_pin A -pin Y -input_transition_rise 0.0320619  -input_transition_fall 0.0213978  [get_ports {u_ahb_ram_genblk3_SRAMADDR[10]}]
set_driving_cell -fall -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXIT2X2MA10TR -from_pin A -pin Y -input_transition_rise 0.0320619  -input_transition_fall 0.0213978  [get_ports {u_ahb_ram_genblk3_SRAMADDR[10]}]
set_input_delay  0.907966 -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[10]}]
set_input_delay  0.87325 -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[10]}]
set_input_delay  0.988771 -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[10]}]
set_input_delay  0.944254 -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[10]}]
set_input_delay  2.29406 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[10]}]
set_input_delay  0.634912 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[10]}]
set_input_delay  2.37487 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[10]}]
set_input_delay  0.704318 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[10]}]
set_driving_cell -rise -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXIT2X1P4MA10TR -from_pin S0 -pin Y -input_transition_rise 0.229051  -input_transition_fall 0.13285  [get_ports {u_ahb_ram_genblk3_SRAMADDR[9]}]
set_driving_cell -fall -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXIT2X1P4MA10TR -from_pin S0 -pin Y -input_transition_rise 0.229051  -input_transition_fall 0.13285  [get_ports {u_ahb_ram_genblk3_SRAMADDR[9]}]
set_driving_cell -rise -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXIT2X1P4MA10TR -from_pin A -pin Y -input_transition_rise 0.0265975  -input_transition_fall 0.0173546  [get_ports {u_ahb_ram_genblk3_SRAMADDR[9]}]
set_driving_cell -fall -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXIT2X1P4MA10TR -from_pin A -pin Y -input_transition_rise 0.0265975  -input_transition_fall 0.0173546  [get_ports {u_ahb_ram_genblk3_SRAMADDR[9]}]
set_input_delay  0.933192 -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[9]}]
set_input_delay  0.891604 -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[9]}]
set_input_delay  1.01607 -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[9]}]
set_input_delay  0.969699 -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[9]}]
set_input_delay  2.31929 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[9]}]
set_input_delay  0.516043 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[9]}]
set_input_delay  2.40216 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[9]}]
set_input_delay  0.593657 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[9]}]
set_driving_cell -rise -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXIT2X1P4MA10TR -from_pin S0 -pin Y -input_transition_rise 0.229752  -input_transition_fall 0.132852  [get_ports {u_ahb_ram_genblk3_SRAMADDR[8]}]
set_driving_cell -fall -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXIT2X1P4MA10TR -from_pin S0 -pin Y -input_transition_rise 0.229752  -input_transition_fall 0.132852  [get_ports {u_ahb_ram_genblk3_SRAMADDR[8]}]
set_driving_cell -rise -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXIT2X1P4MA10TR -from_pin A -pin Y -input_transition_rise 0.0466113  -input_transition_fall 0.0377659  [get_ports {u_ahb_ram_genblk3_SRAMADDR[8]}]
set_driving_cell -fall -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXIT2X1P4MA10TR -from_pin A -pin Y -input_transition_rise 0.0466113  -input_transition_fall 0.0377659  [get_ports {u_ahb_ram_genblk3_SRAMADDR[8]}]
set_input_delay  0.971867 -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[8]}]
set_input_delay  0.929961 -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[8]}]
set_input_delay  1.06977 -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[8]}]
set_input_delay  1.02346 -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[8]}]
set_input_delay  2.35796 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[8]}]
set_input_delay  0.685482 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[8]}]
set_input_delay  2.45586 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[8]}]
set_input_delay  0.805072 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[8]}]
set_driving_cell -rise -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell FRICGX0P7BA10TR -from_pin CK -pin ECK -input_transition_rise 0.0213696  -input_transition_fall 0.0155057  [get_ports {u_ahb_ram_genblk3_SRAMADDR[7]}]
set_driving_cell -fall -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell FRICGX0P7BA10TR -from_pin CK -pin ECK -input_transition_rise 0.0213696  -input_transition_fall 0.0155057  [get_ports {u_ahb_ram_genblk3_SRAMADDR[7]}]
set_driving_cell -rise -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell FRICGX0P7BA10TR -from_pin CK -pin ECK -input_transition_rise 0.0213596  -input_transition_fall 0.0154921  [get_ports {u_ahb_ram_genblk3_SRAMADDR[7]}]
set_driving_cell -fall -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell FRICGX0P7BA10TR -from_pin CK -pin ECK -input_transition_rise 0.0213596  -input_transition_fall 0.0154921  [get_ports {u_ahb_ram_genblk3_SRAMADDR[7]}]
set_input_delay  1.17773 -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[7]}]
set_input_delay  1.13563 -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[7]}]
set_input_delay  1.27224 -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[7]}]
set_input_delay  1.22563 -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[7]}]
set_input_delay  2.56873 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[7]}]
set_input_delay  0.759078 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[7]}]
set_input_delay  2.69207 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[7]}]
set_input_delay  0.848015 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[7]}]
set_driving_cell -rise -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell FRICGX0P7BA10TR -from_pin CK -pin ECK -input_transition_rise 0.0230182  -input_transition_fall 0.0164888  [get_ports {u_ahb_ram_genblk3_SRAMADDR[6]}]
set_driving_cell -fall -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell FRICGX0P7BA10TR -from_pin CK -pin ECK -input_transition_rise 0.0230182  -input_transition_fall 0.0164888  [get_ports {u_ahb_ram_genblk3_SRAMADDR[6]}]
set_driving_cell -rise -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell FRICGX0P7BA10TR -from_pin CK -pin ECK -input_transition_rise 0.0230145  -input_transition_fall 0.0164741  [get_ports {u_ahb_ram_genblk3_SRAMADDR[6]}]
set_driving_cell -fall -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell FRICGX0P7BA10TR -from_pin CK -pin ECK -input_transition_rise 0.0230145  -input_transition_fall 0.0164741  [get_ports {u_ahb_ram_genblk3_SRAMADDR[6]}]
set_input_delay  1.19591 -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[6]}]
set_input_delay  1.15387 -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[6]}]
set_input_delay  1.2955 -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[6]}]
set_input_delay  1.24915 -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[6]}]
set_input_delay  2.60802 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[6]}]
set_input_delay  0.777573 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[6]}]
set_input_delay  2.699 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[6]}]
set_input_delay  0.872734 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[6]}]
set_driving_cell -rise -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell BUFX1P7BA10TR -from_pin A -pin Y -input_transition_rise 0.0167411  -input_transition_fall 0.0130439  [get_ports {u_ahb_ram_genblk3_SRAMADDR[5]}]
set_driving_cell -fall -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell BUFX1P7BA10TR -from_pin A -pin Y -input_transition_rise 0.0167411  -input_transition_fall 0.0130439  [get_ports {u_ahb_ram_genblk3_SRAMADDR[5]}]
set_driving_cell -rise -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell BUFX1P7BA10TR -from_pin A -pin Y -input_transition_rise 0.0167409  -input_transition_fall 0.0130436  [get_ports {u_ahb_ram_genblk3_SRAMADDR[5]}]
set_driving_cell -fall -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell BUFX1P7BA10TR -from_pin A -pin Y -input_transition_rise 0.0167409  -input_transition_fall 0.0130436  [get_ports {u_ahb_ram_genblk3_SRAMADDR[5]}]
set_input_delay  1.06064 -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[5]}]
set_input_delay  1.01661 -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[5]}]
set_input_delay  1.09956 -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[5]}]
set_input_delay  1.05558 -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[5]}]
set_input_delay  2.44673 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[5]}]
set_input_delay  0.635692 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[5]}]
set_input_delay  2.50221 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[5]}]
set_input_delay  0.675922 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[5]}]
set_driving_cell -rise -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXIT2X1P4MA10TR -from_pin S0 -pin Y -input_transition_rise 0.22945  -input_transition_fall 0.133246  [get_ports {u_ahb_ram_genblk3_SRAMADDR[4]}]
set_driving_cell -fall -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXIT2X1P4MA10TR -from_pin S0 -pin Y -input_transition_rise 0.22945  -input_transition_fall 0.133246  [get_ports {u_ahb_ram_genblk3_SRAMADDR[4]}]
set_driving_cell -rise -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXIT2X1P4MA10TR -from_pin A -pin Y -input_transition_rise 0.046034  -input_transition_fall 0.0374284  [get_ports {u_ahb_ram_genblk3_SRAMADDR[4]}]
set_driving_cell -fall -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXIT2X1P4MA10TR -from_pin A -pin Y -input_transition_rise 0.046034  -input_transition_fall 0.0374284  [get_ports {u_ahb_ram_genblk3_SRAMADDR[4]}]
set_input_delay  0.986075 -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[4]}]
set_input_delay  0.944013 -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[4]}]
set_input_delay  1.08959 -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[4]}]
set_input_delay  1.04327 -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[4]}]
set_input_delay  2.37217 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[4]}]
set_input_delay  0.72102 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[4]}]
set_input_delay  2.47569 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[4]}]
set_input_delay  0.845557 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[4]}]
set_driving_cell -rise -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXIT2X2MA10TR -from_pin S0 -pin Y -input_transition_rise 0.229521  -input_transition_fall 0.133327  [get_ports {u_ahb_ram_genblk3_SRAMADDR[3]}]
set_driving_cell -fall -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXIT2X2MA10TR -from_pin S0 -pin Y -input_transition_rise 0.229521  -input_transition_fall 0.133327  [get_ports {u_ahb_ram_genblk3_SRAMADDR[3]}]
set_driving_cell -rise -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXIT2X2MA10TR -from_pin A -pin Y -input_transition_rise 0.0290377  -input_transition_fall 0.01872  [get_ports {u_ahb_ram_genblk3_SRAMADDR[3]}]
set_driving_cell -fall -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXIT2X2MA10TR -from_pin A -pin Y -input_transition_rise 0.0290377  -input_transition_fall 0.01872  [get_ports {u_ahb_ram_genblk3_SRAMADDR[3]}]
set_input_delay  0.891138 -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[3]}]
set_input_delay  0.855483 -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[3]}]
set_input_delay  0.96327 -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[3]}]
set_input_delay  0.917974 -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[3]}]
set_input_delay  2.27724 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[3]}]
set_input_delay  0.48525 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[3]}]
set_input_delay  2.34937 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[3]}]
set_input_delay  0.547127 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[3]}]
set_driving_cell -rise -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell FRICGX0P7BA10TR -from_pin CK -pin ECK -input_transition_rise 0.241301  -input_transition_fall 0.154089  [get_ports {u_ahb_ram_genblk3_SRAMADDR[2]}]
set_driving_cell -fall -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell FRICGX0P7BA10TR -from_pin CK -pin ECK -input_transition_rise 0.241301  -input_transition_fall 0.154089  [get_ports {u_ahb_ram_genblk3_SRAMADDR[2]}]
set_driving_cell -rise -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell FRICGX0P7BA10TR -from_pin CK -pin ECK -input_transition_rise 0.230516  -input_transition_fall 0.122662  [get_ports {u_ahb_ram_genblk3_SRAMADDR[2]}]
set_driving_cell -fall -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell FRICGX0P7BA10TR -from_pin CK -pin ECK -input_transition_rise 0.230516  -input_transition_fall 0.122662  [get_ports {u_ahb_ram_genblk3_SRAMADDR[2]}]
set_input_delay  1.1209 -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[2]}]
set_input_delay  1.07864 -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[2]}]
set_input_delay  1.21307 -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[2]}]
set_input_delay  1.16739 -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[2]}]
set_input_delay  2.507 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[2]}]
set_input_delay  0.803402 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[2]}]
set_input_delay  2.59916 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[2]}]
set_input_delay  0.901656 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[2]}]
set_driving_cell -rise -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell FRICGX0P7BA10TR -from_pin CK -pin ECK -input_transition_rise 0.0172909  -input_transition_fall 0.0132886  [get_ports {u_ahb_ram_genblk3_SRAMADDR[1]}]
set_driving_cell -fall -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell FRICGX0P7BA10TR -from_pin CK -pin ECK -input_transition_rise 0.0172909  -input_transition_fall 0.0132886  [get_ports {u_ahb_ram_genblk3_SRAMADDR[1]}]
set_driving_cell -rise -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell FRICGX0P7BA10TR -from_pin CK -pin ECK -input_transition_rise 0.0172817  -input_transition_fall 0.0132674  [get_ports {u_ahb_ram_genblk3_SRAMADDR[1]}]
set_driving_cell -fall -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell FRICGX0P7BA10TR -from_pin CK -pin ECK -input_transition_rise 0.0172817  -input_transition_fall 0.0132674  [get_ports {u_ahb_ram_genblk3_SRAMADDR[1]}]
set_input_delay  1.23136 -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[1]}]
set_input_delay  1.04863 -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[1]}]
set_input_delay  1.43588 -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[1]}]
set_input_delay  1.16173 -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[1]}]
set_input_delay  2.54315 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[1]}]
set_input_delay  0.70671 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[1]}]
set_input_delay  2.61923 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[1]}]
set_input_delay  0.786189 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[1]}]
set_driving_cell -rise -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXIT2X1P4MA10TR -from_pin S0 -pin Y -input_transition_rise 0.229051  -input_transition_fall 0.13285  [get_ports {u_ahb_ram_genblk3_SRAMADDR[0]}]
set_driving_cell -fall -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXIT2X1P4MA10TR -from_pin S0 -pin Y -input_transition_rise 0.229051  -input_transition_fall 0.13285  [get_ports {u_ahb_ram_genblk3_SRAMADDR[0]}]
set_driving_cell -rise -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXIT2X1P4MA10TR -from_pin A -pin Y -input_transition_rise 0.0418421  -input_transition_fall 0.0348643  [get_ports {u_ahb_ram_genblk3_SRAMADDR[0]}]
set_driving_cell -fall -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell MXIT2X1P4MA10TR -from_pin A -pin Y -input_transition_rise 0.0418421  -input_transition_fall 0.0348643  [get_ports {u_ahb_ram_genblk3_SRAMADDR[0]}]
set_input_delay  1.06673 -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[0]}]
set_input_delay  0.890702 -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[0]}]
set_input_delay  1.28968 -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[0]}]
set_input_delay  1.02165 -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[0]}]
set_input_delay  2.35611 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[0]}]
set_input_delay  0.690185 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[0]}]
set_input_delay  2.48264 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[0]}]
set_input_delay  0.803783 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[0]}]
set_driving_cell -rise -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell BUFX11BA10TR -from_pin A -pin Y -input_transition_rise 0.0302393  -input_transition_fall 0.0265184  [get_ports {gated_hclk}]
set_driving_cell -fall -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell BUFX11BA10TR -from_pin A -pin Y -input_transition_rise 0.0302393  -input_transition_fall 0.0265184  [get_ports {gated_hclk}]
set_driving_cell -rise -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell BUFX11BA10TR -from_pin A -pin Y -input_transition_rise 0.0302393  -input_transition_fall 0.0264034  [get_ports {gated_hclk}]
set_driving_cell -fall -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell BUFX11BA10TR -from_pin A -pin Y -input_transition_rise 0.0302393  -input_transition_fall 0.0264034  [get_ports {gated_hclk}]
set_clock_latency -source -rise  -clock [get_clocks {XTAL1}]  0.141967 [get_ports {gated_hclk}]
set_clock_latency -source -fall -late  -clock [get_clocks {XTAL1}]  0.137811 [get_ports {gated_hclk}]
set_clock_latency -source -fall -early  -clock [get_clocks {XTAL1}]  0.137731 [get_ports {gated_hclk}]
set_propagated_clock [get_pins {u_part_extmem2/u_mem_ext2/u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_mem0/CLK}]
###############################################################################
# Extra setting
###############################################################################
set timing_input_port_default_clock false
set auto_wire_load_selection false
set_wire_load_mode top
###############################################################################
# POCV Information
###############################################################################
