# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# compile CXX with /usr/bin/c++
CXX_FLAGS =  

CXX_DEFINES = 

CXX_INCLUDES = -I/home/wilsonhong/aspdac/Min_cost_solver/Min-Cost-Network-Flow-Lemon/lemon 

