###############################################################################
#
# Created by PrimeTime on Thu Oct  7 17:38:15 2021
#
###############################################################################
# 
# Written by HyperScale Constraint Extractor
# Version : R-2020.09-SP5
# Top design name : cmsdk_mcu
# Block name : MemContext2
# Extraction Mode : normal
# Instance : u_mem_context2
# 
###############################################################################
set_units -time ns -capacitance pF -current mA -voltage V -resistance kOhm -power pW
###############################################################################
#  
# Units
# capacitive_load_unit           : 1 pF
# current_unit                   : 0.001 A
# resistance_unit                : 1 kOhm
# time_unit                      : 1 ns
# voltage_unit                   : 1 V
###############################################################################
set_operating_conditions -analysis_type on_chip_variation  -library [get_libs {scadv10_cln65gp_rvt_tt_1p0v_25c.db:scadv10_cln65gp_rvt_tt_1p0v_25c}] 
create_clock -name XTAL1 -period 2.5 -waveform { 0 1.25 } -add [get_ports {gated_hclk}]
###############################################################################
#
# Created by pt_shell on Thu Oct  7 17:38:15 2021
#
###############################################################################
# 
# Written by HyperScale Constraint Extractor
# Version : R-2020.09-SP5
# Top design name : cmsdk_mcu
# Block name : MemContext2
# Extraction Mode : normal
# Instance : u_mem_context2
# 
###############################################################################
set_clock_map XTAL1 -parent_clock XTAL1
###############################################################################
# Boundary Context Information
###############################################################################
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[7]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[6]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[5]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[4]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[3]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[2]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[1]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[0]}]
set_max_capacitance  2.443564 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_chip_select}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_chip_select}]
set_max_capacitance  2.443564 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_n2}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_n2}]
set_max_capacitance  2.443564 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[31]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[31]}]
set_max_capacitance  2.443564 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[30]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[30]}]
set_max_capacitance  2.443564 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[29]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[29]}]
set_max_capacitance  2.443564 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[28]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[28]}]
set_max_capacitance  2.443564 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[27]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[27]}]
set_max_capacitance  2.443564 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[26]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[26]}]
set_max_capacitance  2.443564 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[25]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[25]}]
set_max_capacitance  2.443564 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[24]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMWDATA[24]}]
set_max_capacitance  2.443564 [get_ports {u_ahb_ram_genblk3_SRAMADDR[11]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMADDR[11]}]
set_max_capacitance  2.443564 [get_ports {u_ahb_ram_genblk3_SRAMADDR[10]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMADDR[10]}]
set_max_capacitance  2.443564 [get_ports {u_ahb_ram_genblk3_SRAMADDR[9]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMADDR[9]}]
set_max_capacitance  2.443564 [get_ports {u_ahb_ram_genblk3_SRAMADDR[8]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMADDR[8]}]
set_max_capacitance  2.443564 [get_ports {u_ahb_ram_genblk3_SRAMADDR[7]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMADDR[7]}]
set_max_capacitance  2.443564 [get_ports {u_ahb_ram_genblk3_SRAMADDR[6]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMADDR[6]}]
set_max_capacitance  2.443564 [get_ports {u_ahb_ram_genblk3_SRAMADDR[5]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMADDR[5]}]
set_max_capacitance  2.443564 [get_ports {u_ahb_ram_genblk3_SRAMADDR[4]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMADDR[4]}]
set_max_capacitance  2.443564 [get_ports {u_ahb_ram_genblk3_SRAMADDR[3]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMADDR[3]}]
set_max_capacitance  2.443564 [get_ports {u_ahb_ram_genblk3_SRAMADDR[2]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMADDR[2]}]
set_max_capacitance  2.443564 [get_ports {u_ahb_ram_genblk3_SRAMADDR[1]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMADDR[1]}]
set_max_capacitance  2.443564 [get_ports {u_ahb_ram_genblk3_SRAMADDR[0]}]
set_max_transition  0.699428 [get_ports {u_ahb_ram_genblk3_SRAMADDR[0]}]
set_max_capacitance  0.916337 [get_ports {gated_hclk}]
set_max_transition  0.699428 [get_ports {gated_hclk}]
set_output_delay  0.498816 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[7]}]
set_output_delay  0.074756 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[7]}]
set_output_delay  0.482373 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[7]}]
set_output_delay  0.071218 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[7]}]
set_load -pin_load -max  0.001733 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[7]}]
set_load -pin_load -max  0.001733 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[7]}]
set_load -pin_load -min  0.001733 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[7]}]
set_load -pin_load -min  0.001733 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[7]}]
set_output_delay  0.495072 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[6]}]
set_output_delay  0.079716 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[6]}]
set_output_delay  0.487686 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[6]}]
set_output_delay  0.079836 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[6]}]
set_load -pin_load -max  0.001087 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[6]}]
set_load -pin_load -max  0.001087 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[6]}]
set_load -pin_load -min  0.001087 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[6]}]
set_load -pin_load -min  0.001087 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[6]}]
set_output_delay  0.495236 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[5]}]
set_output_delay  0.070864 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[5]}]
set_output_delay  0.473089 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[5]}]
set_output_delay  0.073592 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[5]}]
set_load -pin_load -max  0.001087 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[5]}]
set_load -pin_load -max  0.001087 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[5]}]
set_load -pin_load -min  0.001087 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[5]}]
set_load -pin_load -min  0.001087 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[5]}]
set_output_delay  0.563542 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[4]}]
set_output_delay  0.129164 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[4]}]
set_output_delay  0.529857 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[4]}]
set_output_delay  0.122612 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[4]}]
set_load -pin_load -max  0.001915 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[4]}]
set_load -pin_load -max  0.001915 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[4]}]
set_load -pin_load -min  0.001915 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[4]}]
set_load -pin_load -min  0.001915 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[4]}]
set_output_delay  0.481581 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[3]}]
set_output_delay  0.121016 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[3]}]
set_output_delay  0.491715 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[3]}]
set_output_delay  0.121003 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[3]}]
set_load -pin_load -max  0.001087 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[3]}]
set_load -pin_load -max  0.001087 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[3]}]
set_load -pin_load -min  0.001087 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[3]}]
set_load -pin_load -min  0.001087 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[3]}]
set_output_delay  0.499946 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[2]}]
set_output_delay  0.14776 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[2]}]
set_output_delay  0.48862 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[2]}]
set_output_delay  0.139367 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[2]}]
set_load -pin_load -max  0.001087 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[2]}]
set_load -pin_load -max  0.001087 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[2]}]
set_load -pin_load -min  0.001087 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[2]}]
set_load -pin_load -min  0.001087 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[2]}]
set_output_delay  0.499295 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[1]}]
set_output_delay  0.101389 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[1]}]
set_output_delay  0.484667 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[1]}]
set_output_delay  0.10152 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[1]}]
set_load -pin_load -max  0.001087 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[1]}]
set_load -pin_load -max  0.001087 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[1]}]
set_load -pin_load -min  0.001087 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[1]}]
set_load -pin_load -min  0.001087 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[1]}]
set_output_delay  0.498633 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[0]}]
set_output_delay  0.097856 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[0]}]
set_output_delay  0.480937 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[0]}]
set_output_delay  0.094606 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[0]}]
set_load -pin_load -max  0.001087 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[0]}]
set_load -pin_load -max  0.001087 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[0]}]
set_load -pin_load -min  0.001087 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[0]}]
set_load -pin_load -min  0.001087 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_data_out[0]}]
set_input_delay  1.155484 -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_chip_select}]
set_input_delay  0.819146 -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_chip_select}]
set_input_delay  1.179495 -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_chip_select}]
set_input_delay  0.798038 -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_chip_select}]
set_input_delay  2.522861 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_chip_select}]
set_input_delay  0.693989 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_chip_select}]
set_input_delay  2.563855 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_chip_select}]
set_input_delay  0.670146 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_chip_select}]
set_driving_cell -rise -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.135237  -input_transition_fall 0.073555  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_chip_select}]
set_driving_cell -fall -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.135237  -input_transition_fall 0.073555  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_chip_select}]
set_driving_cell -rise -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.135237  -input_transition_fall 0.073555  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_chip_select}]
set_driving_cell -fall -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.135237  -input_transition_fall 0.073555  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_chip_select}]
set_case_analysis 1 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3__Logic1_}]
set_case_analysis 0 [get_ports {u_ahb_ram_genblk3_u_fpga_sram_sBRAM3__Logic0_}]
set_input_delay  1.192179 -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_n2}]
set_input_delay  1.116186 -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_n2}]
set_input_delay  1.208134 -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_n2}]
set_input_delay  1.09543 -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_n2}]
set_input_delay  2.54316 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_n2}]
set_input_delay  0.684944 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_n2}]
set_input_delay  2.592495 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_n2}]
set_input_delay  0.663697 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_u_fpga_sram_n2}]
set_driving_cell -rise -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.144747  -input_transition_fall 0.078642  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_n2}]
set_driving_cell -fall -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.144747  -input_transition_fall 0.078642  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_n2}]
set_driving_cell -rise -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.144747  -input_transition_fall 0.078642  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_n2}]
set_driving_cell -fall -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.144747  -input_transition_fall 0.078642  [get_ports {u_ahb_ram_genblk3_u_fpga_sram_n2}]
set_input_delay  0.82006 -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[31]}]
set_input_delay  0.780573 -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[31]}]
set_input_delay  0.867568 -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[31]}]
set_input_delay  0.852034 -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[31]}]
set_input_delay  1.652908 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[31]}]
set_input_delay  0.488051 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[31]}]
set_input_delay  1.677864 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[31]}]
set_input_delay  0.478066 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[31]}]
set_driving_cell -rise -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.137651  -input_transition_fall 0.074844  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[31]}]
set_driving_cell -fall -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.137651  -input_transition_fall 0.074844  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[31]}]
set_driving_cell -rise -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.137651  -input_transition_fall 0.074843  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[31]}]
set_driving_cell -fall -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.137651  -input_transition_fall 0.074843  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[31]}]
set_input_delay  0.799487 -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[30]}]
set_input_delay  0.764608 -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[30]}]
set_input_delay  0.852289 -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[30]}]
set_input_delay  0.835349 -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[30]}]
set_input_delay  1.671827 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[30]}]
set_input_delay  0.523203 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[30]}]
set_input_delay  1.69467 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[30]}]
set_input_delay  0.514787 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[30]}]
set_driving_cell -rise -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.135752  -input_transition_fall 0.073854  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[30]}]
set_driving_cell -fall -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.135752  -input_transition_fall 0.073854  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[30]}]
set_driving_cell -rise -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.135752  -input_transition_fall 0.073854  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[30]}]
set_driving_cell -fall -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.135752  -input_transition_fall 0.073854  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[30]}]
set_input_delay  0.808566 -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[29]}]
set_input_delay  0.770577 -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[29]}]
set_input_delay  0.850278 -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[29]}]
set_input_delay  0.834587 -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[29]}]
set_input_delay  1.656462 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[29]}]
set_input_delay  0.519311 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[29]}]
set_input_delay  1.680999 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[29]}]
set_input_delay  0.506988 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[29]}]
set_driving_cell -rise -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.1376  -input_transition_fall 0.074815  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[29]}]
set_driving_cell -fall -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.1376  -input_transition_fall 0.074815  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[29]}]
set_driving_cell -rise -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.137599  -input_transition_fall 0.074815  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[29]}]
set_driving_cell -fall -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.137599  -input_transition_fall 0.074815  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[29]}]
set_input_delay  0.815982 -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[28]}]
set_input_delay  0.778806 -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[28]}]
set_input_delay  0.867323 -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[28]}]
set_input_delay  0.851586 -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[28]}]
set_input_delay  1.672431 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[28]}]
set_input_delay  0.51742 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[28]}]
set_input_delay  1.690735 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[28]}]
set_input_delay  0.509647 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[28]}]
set_driving_cell -rise -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.135725  -input_transition_fall 0.073822  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[28]}]
set_driving_cell -fall -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.135725  -input_transition_fall 0.073822  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[28]}]
set_driving_cell -rise -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.135725  -input_transition_fall 0.073821  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[28]}]
set_driving_cell -fall -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.135725  -input_transition_fall 0.073821  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[28]}]
set_input_delay  0.813689 -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[27]}]
set_input_delay  0.778727 -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[27]}]
set_input_delay  0.86436 -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[27]}]
set_input_delay  0.84861 -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[27]}]
set_input_delay  1.659185 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[27]}]
set_input_delay  0.504099 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[27]}]
set_input_delay  1.685697 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[27]}]
set_input_delay  0.491216 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[27]}]
set_driving_cell -rise -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.134004  -input_transition_fall 0.072908  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[27]}]
set_driving_cell -fall -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.134004  -input_transition_fall 0.072908  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[27]}]
set_driving_cell -rise -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.134004  -input_transition_fall 0.072908  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[27]}]
set_driving_cell -fall -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.134004  -input_transition_fall 0.072908  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[27]}]
set_input_delay  0.778529 -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[26]}]
set_input_delay  0.7501 -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[26]}]
set_input_delay  0.839968 -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[26]}]
set_input_delay  0.828225 -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[26]}]
set_input_delay  1.620193 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[26]}]
set_input_delay  0.492244 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[26]}]
set_input_delay  1.662076 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[26]}]
set_input_delay  0.48577 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[26]}]
set_driving_cell -rise -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.13398  -input_transition_fall 0.072897  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[26]}]
set_driving_cell -fall -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.13398  -input_transition_fall 0.072897  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[26]}]
set_driving_cell -rise -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.13398  -input_transition_fall 0.072896  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[26]}]
set_driving_cell -fall -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.13398  -input_transition_fall 0.072896  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[26]}]
set_input_delay  0.777206 -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[25]}]
set_input_delay  0.742356 -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[25]}]
set_input_delay  0.831774 -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[25]}]
set_input_delay  0.816814 -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[25]}]
set_input_delay  1.656805 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[25]}]
set_input_delay  0.49644 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[25]}]
set_input_delay  1.697672 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[25]}]
set_input_delay  0.487051 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[25]}]
set_driving_cell -rise -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.136148  -input_transition_fall 0.074033  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[25]}]
set_driving_cell -fall -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.136148  -input_transition_fall 0.074033  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[25]}]
set_driving_cell -rise -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.136147  -input_transition_fall 0.074033  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[25]}]
set_driving_cell -fall -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.136147  -input_transition_fall 0.074033  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[25]}]
set_input_delay  0.846823 -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[24]}]
set_input_delay  0.810999 -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[24]}]
set_input_delay  0.927141 -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[24]}]
set_input_delay  0.907967 -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[24]}]
set_input_delay  1.697151 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[24]}]
set_input_delay  0.509775 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[24]}]
set_input_delay  1.737606 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[24]}]
set_input_delay  0.508345 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMWDATA[24]}]
set_driving_cell -rise -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.136728  -input_transition_fall 0.075292  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[24]}]
set_driving_cell -fall -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.136728  -input_transition_fall 0.075292  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[24]}]
set_driving_cell -rise -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.136728  -input_transition_fall 0.075292  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[24]}]
set_driving_cell -fall -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.136728  -input_transition_fall 0.075292  [get_ports {u_ahb_ram_genblk3_SRAMWDATA[24]}]
set_input_delay  1.07533 -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[11]}]
set_input_delay  1.004624 -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[11]}]
set_input_delay  1.080628 -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[11]}]
set_input_delay  1.00473 -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[11]}]
set_input_delay  2.459692 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[11]}]
set_input_delay  0.648098 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[11]}]
set_input_delay  2.464989 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[11]}]
set_input_delay  0.64858 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[11]}]
set_driving_cell -rise -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.151309  -input_transition_fall 0.082212  [get_ports {u_ahb_ram_genblk3_SRAMADDR[11]}]
set_driving_cell -fall -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.151309  -input_transition_fall 0.082212  [get_ports {u_ahb_ram_genblk3_SRAMADDR[11]}]
set_driving_cell -rise -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.151311  -input_transition_fall 0.082212  [get_ports {u_ahb_ram_genblk3_SRAMADDR[11]}]
set_driving_cell -fall -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.151311  -input_transition_fall 0.082212  [get_ports {u_ahb_ram_genblk3_SRAMADDR[11]}]
set_input_delay  1.053954 -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[10]}]
set_input_delay  0.986391 -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[10]}]
set_input_delay  1.060158 -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[10]}]
set_input_delay  0.987747 -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[10]}]
set_input_delay  2.438315 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[10]}]
set_input_delay  0.632131 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[10]}]
set_input_delay  2.444519 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[10]}]
set_input_delay  0.634016 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[10]}]
set_driving_cell -rise -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.149749  -input_transition_fall 0.082213  [get_ports {u_ahb_ram_genblk3_SRAMADDR[10]}]
set_driving_cell -fall -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.149749  -input_transition_fall 0.082213  [get_ports {u_ahb_ram_genblk3_SRAMADDR[10]}]
set_driving_cell -rise -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.149751  -input_transition_fall 0.082196  [get_ports {u_ahb_ram_genblk3_SRAMADDR[10]}]
set_driving_cell -fall -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.149751  -input_transition_fall 0.082196  [get_ports {u_ahb_ram_genblk3_SRAMADDR[10]}]
set_input_delay  0.956389 -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[9]}]
set_input_delay  0.885928 -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[9]}]
set_input_delay  1.010393 -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[9]}]
set_input_delay  0.933666 -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[9]}]
set_input_delay  2.34075 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[9]}]
set_input_delay  0.533688 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[9]}]
set_input_delay  2.394755 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[9]}]
set_input_delay  0.581937 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[9]}]
set_driving_cell -rise -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.094008  -input_transition_fall 0.114926  [get_ports {u_ahb_ram_genblk3_SRAMADDR[9]}]
set_driving_cell -fall -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.094008  -input_transition_fall 0.114926  [get_ports {u_ahb_ram_genblk3_SRAMADDR[9]}]
set_driving_cell -rise -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.085126  -input_transition_fall 0.110788  [get_ports {u_ahb_ram_genblk3_SRAMADDR[9]}]
set_driving_cell -fall -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.085126  -input_transition_fall 0.110788  [get_ports {u_ahb_ram_genblk3_SRAMADDR[9]}]
set_input_delay  1.053264 -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[8]}]
set_input_delay  1.00587 -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[8]}]
set_input_delay  1.081569 -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[8]}]
set_input_delay  1.029786 -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[8]}]
set_input_delay  2.437625 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[8]}]
set_input_delay  0.659747 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[8]}]
set_input_delay  2.46593 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[8]}]
set_input_delay  0.676215 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[8]}]
set_driving_cell -rise -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.143235  -input_transition_fall 0.077871  [get_ports {u_ahb_ram_genblk3_SRAMADDR[8]}]
set_driving_cell -fall -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.143235  -input_transition_fall 0.077871  [get_ports {u_ahb_ram_genblk3_SRAMADDR[8]}]
set_driving_cell -rise -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.143235  -input_transition_fall 0.077871  [get_ports {u_ahb_ram_genblk3_SRAMADDR[8]}]
set_driving_cell -fall -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.143235  -input_transition_fall 0.077871  [get_ports {u_ahb_ram_genblk3_SRAMADDR[8]}]
set_input_delay  0.956565 -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[7]}]
set_input_delay  0.909491 -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[7]}]
set_input_delay  1.017066 -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[7]}]
set_input_delay  0.966407 -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[7]}]
set_input_delay  2.340926 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[7]}]
set_input_delay  0.538551 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[7]}]
set_input_delay  2.401428 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[7]}]
set_input_delay  0.592222 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[7]}]
set_driving_cell -rise -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.084925  -input_transition_fall 0.089439  [get_ports {u_ahb_ram_genblk3_SRAMADDR[7]}]
set_driving_cell -fall -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.084925  -input_transition_fall 0.089439  [get_ports {u_ahb_ram_genblk3_SRAMADDR[7]}]
set_driving_cell -rise -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.084923  -input_transition_fall 0.089435  [get_ports {u_ahb_ram_genblk3_SRAMADDR[7]}]
set_driving_cell -fall -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.084923  -input_transition_fall 0.089435  [get_ports {u_ahb_ram_genblk3_SRAMADDR[7]}]
set_input_delay  1.095769 -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[6]}]
set_input_delay  1.023219 -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[6]}]
set_input_delay  1.099743 -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[6]}]
set_input_delay  1.024009 -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[6]}]
set_input_delay  2.48013 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[6]}]
set_input_delay  0.668335 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[6]}]
set_input_delay  2.484105 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[6]}]
set_input_delay  0.669634 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[6]}]
set_driving_cell -rise -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.149497  -input_transition_fall 0.081487  [get_ports {u_ahb_ram_genblk3_SRAMADDR[6]}]
set_driving_cell -fall -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.149497  -input_transition_fall 0.081487  [get_ports {u_ahb_ram_genblk3_SRAMADDR[6]}]
set_driving_cell -rise -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.149499  -input_transition_fall 0.081434  [get_ports {u_ahb_ram_genblk3_SRAMADDR[6]}]
set_driving_cell -fall -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.149499  -input_transition_fall 0.081434  [get_ports {u_ahb_ram_genblk3_SRAMADDR[6]}]
set_input_delay  1.078435 -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[5]}]
set_input_delay  1.031173 -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[5]}]
set_input_delay  1.112855 -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[5]}]
set_input_delay  1.059783 -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[5]}]
set_input_delay  2.462796 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[5]}]
set_input_delay  0.687041 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[5]}]
set_input_delay  2.497217 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[5]}]
set_input_delay  0.709464 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[5]}]
set_driving_cell -rise -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.158706  -input_transition_fall 0.086292  [get_ports {u_ahb_ram_genblk3_SRAMADDR[5]}]
set_driving_cell -fall -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.158706  -input_transition_fall 0.086292  [get_ports {u_ahb_ram_genblk3_SRAMADDR[5]}]
set_driving_cell -rise -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.158706  -input_transition_fall 0.086292  [get_ports {u_ahb_ram_genblk3_SRAMADDR[5]}]
set_driving_cell -fall -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.158706  -input_transition_fall 0.086292  [get_ports {u_ahb_ram_genblk3_SRAMADDR[5]}]
set_input_delay  0.950841 -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[4]}]
set_input_delay  0.903874 -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[4]}]
set_input_delay  1.016913 -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[4]}]
set_input_delay  0.963119 -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[4]}]
set_input_delay  2.335202 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[4]}]
set_input_delay  0.564412 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[4]}]
set_input_delay  2.401274 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[4]}]
set_input_delay  0.61583 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[4]}]
set_driving_cell -rise -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.087577  -input_transition_fall 0.092188  [get_ports {u_ahb_ram_genblk3_SRAMADDR[4]}]
set_driving_cell -fall -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.087577  -input_transition_fall 0.092188  [get_ports {u_ahb_ram_genblk3_SRAMADDR[4]}]
set_driving_cell -rise -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.087575  -input_transition_fall 0.092184  [get_ports {u_ahb_ram_genblk3_SRAMADDR[4]}]
set_driving_cell -fall -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.087575  -input_transition_fall 0.092184  [get_ports {u_ahb_ram_genblk3_SRAMADDR[4]}]
set_input_delay  0.96705 -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[3]}]
set_input_delay  0.917724 -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[3]}]
set_input_delay  1.016382 -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[3]}]
set_input_delay  0.967582 -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[3]}]
set_input_delay  2.351411 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[3]}]
set_input_delay  0.559726 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[3]}]
set_input_delay  2.400743 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[3]}]
set_input_delay  0.611177 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[3]}]
set_driving_cell -rise -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.081023  -input_transition_fall 0.082836  [get_ports {u_ahb_ram_genblk3_SRAMADDR[3]}]
set_driving_cell -fall -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.081023  -input_transition_fall 0.082836  [get_ports {u_ahb_ram_genblk3_SRAMADDR[3]}]
set_driving_cell -rise -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.080993  -input_transition_fall 0.082826  [get_ports {u_ahb_ram_genblk3_SRAMADDR[3]}]
set_driving_cell -fall -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.080993  -input_transition_fall 0.082826  [get_ports {u_ahb_ram_genblk3_SRAMADDR[3]}]
set_input_delay  0.942068 -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[2]}]
set_input_delay  0.892744 -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[2]}]
set_input_delay  1.006491 -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[2]}]
set_input_delay  0.950502 -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[2]}]
set_input_delay  2.363882 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[2]}]
set_input_delay  0.555287 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[2]}]
set_input_delay  2.390852 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[2]}]
set_input_delay  0.603296 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[2]}]
set_driving_cell -rise -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.090041  -input_transition_fall 0.094213  [get_ports {u_ahb_ram_genblk3_SRAMADDR[2]}]
set_driving_cell -fall -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.090041  -input_transition_fall 0.094213  [get_ports {u_ahb_ram_genblk3_SRAMADDR[2]}]
set_driving_cell -rise -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.090039  -input_transition_fall 0.094211  [get_ports {u_ahb_ram_genblk3_SRAMADDR[2]}]
set_driving_cell -fall -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.090039  -input_transition_fall 0.094211  [get_ports {u_ahb_ram_genblk3_SRAMADDR[2]}]
set_input_delay  1.155743 -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[1]}]
set_input_delay  0.987083 -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[1]}]
set_input_delay  1.229006 -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[1]}]
set_input_delay  1.047698 -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[1]}]
set_input_delay  2.454668 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[1]}]
set_input_delay  0.650403 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[1]}]
set_input_delay  2.483097 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[1]}]
set_input_delay  0.671003 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[1]}]
set_driving_cell -rise -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.15044  -input_transition_fall 0.081765  [get_ports {u_ahb_ram_genblk3_SRAMADDR[1]}]
set_driving_cell -fall -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.15044  -input_transition_fall 0.081765  [get_ports {u_ahb_ram_genblk3_SRAMADDR[1]}]
set_driving_cell -rise -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.15044  -input_transition_fall 0.081765  [get_ports {u_ahb_ram_genblk3_SRAMADDR[1]}]
set_driving_cell -fall -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.15044  -input_transition_fall 0.081765  [get_ports {u_ahb_ram_genblk3_SRAMADDR[1]}]
set_input_delay  1.130431 -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[0]}]
set_input_delay  0.957805 -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[0]}]
set_input_delay  1.242065 -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[0]}]
set_input_delay  1.030594 -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[0]}]
set_input_delay  2.435977 -clock [get_clocks {XTAL1}] -fall -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[0]}]
set_input_delay  0.642892 -clock [get_clocks {XTAL1}] -fall -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[0]}]
set_input_delay  2.467716 -clock [get_clocks {XTAL1}] -rise -max -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[0]}]
set_input_delay  0.661694 -clock [get_clocks {XTAL1}] -rise -min -add_delay -network_latency_included -source_latency_included [get_ports {u_ahb_ram_genblk3_SRAMADDR[0]}]
set_driving_cell -rise -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.147581  -input_transition_fall 0.080198  [get_ports {u_ahb_ram_genblk3_SRAMADDR[0]}]
set_driving_cell -fall -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.147581  -input_transition_fall 0.080198  [get_ports {u_ahb_ram_genblk3_SRAMADDR[0]}]
set_driving_cell -rise -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.147581  -input_transition_fall 0.080198  [get_ports {u_ahb_ram_genblk3_SRAMADDR[0]}]
set_driving_cell -fall -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell INVX16BA10TR -from_pin A -pin Y -input_transition_rise 0.147581  -input_transition_fall 0.080198  [get_ports {u_ahb_ram_genblk3_SRAMADDR[0]}]
set_clock_latency -source -rise  -clock [get_clocks {XTAL1}]  0.223455 [get_ports {gated_hclk}]
set_clock_latency -source -fall -late  -clock [get_clocks {XTAL1}]  0.217922 [get_ports {gated_hclk}]
set_clock_latency -source -fall -early  -clock [get_clocks {XTAL1}]  0.217595 [get_ports {gated_hclk}]
set_driving_cell -rise -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell BUFX6BA10TR -from_pin A -pin Y -input_transition_rise 0.056097  -input_transition_fall 0.04891  [get_ports {gated_hclk}]
set_driving_cell -fall -max -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell BUFX6BA10TR -from_pin A -pin Y -input_transition_rise 0.056097  -input_transition_fall 0.04891  [get_ports {gated_hclk}]
set_driving_cell -rise -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell BUFX6BA10TR -from_pin A -pin Y -input_transition_rise 0.056097  -input_transition_fall 0.04794  [get_ports {gated_hclk}]
set_driving_cell -fall -min -library scadv10_cln65gp_rvt_tt_1p0v_25c -lib_cell BUFX6BA10TR -from_pin A -pin Y -input_transition_rise 0.056097  -input_transition_fall 0.04794  [get_ports {gated_hclk}]
set_propagated_clock [get_pins {u_part_extmem2/u_mem_ext2/u_ahb_ram_genblk3_u_fpga_sram_sBRAM3_mem0/CLK}]
###############################################################################
# Extra setting
###############################################################################
set timing_input_port_default_clock false
set auto_wire_load_selection false
set_wire_load_mode top
###############################################################################
# POCV Information
###############################################################################
