CC          := g++

CXXFLAGS        := -g -Wall -std=c++17

.DEFAULT_GOAL	:= default

default:
		@echo "build Test"
		$(CC) $(CXXFLAGS) -I ./src ./src/main.cc ./src/astar.cc ./src/graph.cc  -pthread -o ./bin/astart


		
